/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_TapTrade_WRAP_H_
#define SWIG_TapTrade_WRAP_H_

class SwigDirector_ITapTradeAPINotify : public ITapTradeAPINotify, public Swig::Director {

public:
    SwigDirector_ITapTradeAPINotify();
    SwigDirector_ITapTradeAPINotify(ITapTradeAPINotify const &other);
    virtual void TAP_CDECL OnConnect();
    virtual void TAP_CDECL OnRspLogin(TAPIINT32 errorCode, TapAPITradeLoginRspInfo const *loginRspInfo);
    virtual void TAP_CDECL OnAPIReady();
    virtual void TAP_CDECL OnDisconnect(TAPIINT32 reasonCode);
    virtual void TAP_CDECL OnRspChangePassword(TAPIUINT32 sessionID, TAPIINT32 errorCode);
    virtual void TAP_CDECL OnRspSetReservedInfo(TAPIUINT32 sessionID, TAPIINT32 errorCode, TAPISTR_50 const info);
    virtual void TAP_CDECL OnRspQryAccount(TAPIUINT32 sessionID, TAPIUINT32 errorCode, TAPIYNFLAG isLast, TapAPIAccountInfo const *info);
    virtual void TAP_CDECL OnRspQryFund(TAPIUINT32 sessionID, TAPIINT32 errorCode, TAPIYNFLAG isLast, TapAPIFundData const *info);
    virtual void TAP_CDECL OnRtnFund(TapAPIFundData const *info);
    virtual void TAP_CDECL OnRspQryExchange(TAPIUINT32 sessionID, TAPIINT32 errorCode, TAPIYNFLAG isLast, TapAPIExchangeInfo const *info);
    virtual void TAP_CDECL OnRspQryCommodity(TAPIUINT32 sessionID, TAPIINT32 errorCode, TAPIYNFLAG isLast, TapAPICommodityInfo const *info);
    virtual void TAP_CDECL OnRspQryContract(TAPIUINT32 sessionID, TAPIINT32 errorCode, TAPIYNFLAG isLast, TapAPITradeContractInfo const *info);
    virtual void TAP_CDECL OnRtnContract(TapAPITradeContractInfo const *info);
    virtual void TAP_CDECL OnRtnOrder(TapAPIOrderInfoNotice const *info);
    virtual void TAP_CDECL OnRspOrderAction(TAPIUINT32 sessionID, TAPIUINT32 errorCode, TapAPIOrderActionRsp const *info);
    virtual void TAP_CDECL OnRspQryOrder(TAPIUINT32 sessionID, TAPIINT32 errorCode, TAPIYNFLAG isLast, TapAPIOrderInfo const *info);
    virtual void TAP_CDECL OnRspQryOrderProcess(TAPIUINT32 sessionID, TAPIINT32 errorCode, TAPIYNFLAG isLast, TapAPIOrderInfo const *info);
    virtual void TAP_CDECL OnRspQryFill(TAPIUINT32 sessionID, TAPIINT32 errorCode, TAPIYNFLAG isLast, TapAPIFillInfo const *info);
    virtual void TAP_CDECL OnRtnFill(TapAPIFillInfo const *info);
    virtual void TAP_CDECL OnRspQryPosition(TAPIUINT32 sessionID, TAPIINT32 errorCode, TAPIYNFLAG isLast, TapAPIPositionInfo const *info);
    virtual void TAP_CDECL OnRtnPosition(TapAPIPositionInfo const *info);
    virtual void TAP_CDECL OnRspQryClose(TAPIUINT32 sessionID, TAPIINT32 errorCode, TAPIYNFLAG isLast, TapAPICloseInfo const *info);
    virtual void TAP_CDECL OnRtnClose(TapAPICloseInfo const *info);
    virtual void TAP_CDECL OnRtnPositionProfit(TapAPIPositionProfitNotice const *info);
    virtual void TAP_CDECL OnRspQryDeepQuote(TAPIUINT32 sessionID, TAPIINT32 errorCode, TAPIYNFLAG isLast, TapAPIDeepQuoteQryRsp const *info);
    virtual void TAP_CDECL OnRspQryExchangeStateInfo(TAPIUINT32 sessionID, TAPIINT32 errorCode, TAPIYNFLAG isLast, TapAPIExchangeStateInfo const *info);
    virtual void TAP_CDECL OnRtnExchangeStateInfo(TapAPIExchangeStateInfoNotice const *info);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(int, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(int);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(unsigned int, int);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(unsigned int, int, char *);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)(unsigned int, unsigned int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback7_t)(unsigned int, int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback8_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback9_t)(unsigned int, int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback10_t)(unsigned int, int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback11_t)(unsigned int, int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback12_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback13_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback14_t)(unsigned int, unsigned int, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback15_t)(unsigned int, int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback16_t)(unsigned int, int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback17_t)(unsigned int, int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback18_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback19_t)(unsigned int, int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback20_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback21_t)(unsigned int, int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback22_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback23_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback24_t)(unsigned int, int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback25_t)(unsigned int, int, char, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback26_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackOnConnect, SWIG_Callback1_t callbackOnRspLogin, SWIG_Callback2_t callbackOnAPIReady, SWIG_Callback3_t callbackOnDisconnect, SWIG_Callback4_t callbackOnRspChangePassword, SWIG_Callback5_t callbackOnRspSetReservedInfo, SWIG_Callback6_t callbackOnRspQryAccount, SWIG_Callback7_t callbackOnRspQryFund, SWIG_Callback8_t callbackOnRtnFund, SWIG_Callback9_t callbackOnRspQryExchange, SWIG_Callback10_t callbackOnRspQryCommodity, SWIG_Callback11_t callbackOnRspQryContract, SWIG_Callback12_t callbackOnRtnContract, SWIG_Callback13_t callbackOnRtnOrder, SWIG_Callback14_t callbackOnRspOrderAction, SWIG_Callback15_t callbackOnRspQryOrder, SWIG_Callback16_t callbackOnRspQryOrderProcess, SWIG_Callback17_t callbackOnRspQryFill, SWIG_Callback18_t callbackOnRtnFill, SWIG_Callback19_t callbackOnRspQryPosition, SWIG_Callback20_t callbackOnRtnPosition, SWIG_Callback21_t callbackOnRspQryClose, SWIG_Callback22_t callbackOnRtnClose, SWIG_Callback23_t callbackOnRtnPositionProfit, SWIG_Callback24_t callbackOnRspQryDeepQuote, SWIG_Callback25_t callbackOnRspQryExchangeStateInfo, SWIG_Callback26_t callbackOnRtnExchangeStateInfo);

private:
    SWIG_Callback0_t swig_callbackOnConnect;
    SWIG_Callback1_t swig_callbackOnRspLogin;
    SWIG_Callback2_t swig_callbackOnAPIReady;
    SWIG_Callback3_t swig_callbackOnDisconnect;
    SWIG_Callback4_t swig_callbackOnRspChangePassword;
    SWIG_Callback5_t swig_callbackOnRspSetReservedInfo;
    SWIG_Callback6_t swig_callbackOnRspQryAccount;
    SWIG_Callback7_t swig_callbackOnRspQryFund;
    SWIG_Callback8_t swig_callbackOnRtnFund;
    SWIG_Callback9_t swig_callbackOnRspQryExchange;
    SWIG_Callback10_t swig_callbackOnRspQryCommodity;
    SWIG_Callback11_t swig_callbackOnRspQryContract;
    SWIG_Callback12_t swig_callbackOnRtnContract;
    SWIG_Callback13_t swig_callbackOnRtnOrder;
    SWIG_Callback14_t swig_callbackOnRspOrderAction;
    SWIG_Callback15_t swig_callbackOnRspQryOrder;
    SWIG_Callback16_t swig_callbackOnRspQryOrderProcess;
    SWIG_Callback17_t swig_callbackOnRspQryFill;
    SWIG_Callback18_t swig_callbackOnRtnFill;
    SWIG_Callback19_t swig_callbackOnRspQryPosition;
    SWIG_Callback20_t swig_callbackOnRtnPosition;
    SWIG_Callback21_t swig_callbackOnRspQryClose;
    SWIG_Callback22_t swig_callbackOnRtnClose;
    SWIG_Callback23_t swig_callbackOnRtnPositionProfit;
    SWIG_Callback24_t swig_callbackOnRspQryDeepQuote;
    SWIG_Callback25_t swig_callbackOnRspQryExchangeStateInfo;
    SWIG_Callback26_t swig_callbackOnRtnExchangeStateInfo;
    void swig_init_callbacks();
};


#endif
