/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace TapQuoteAPI {

using System;
using System.Runtime.InteropServices;

public class TapAPIQuoteWhole : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIQuoteWhole(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TapAPIQuoteWhole obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPIQuoteWhole() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapQuotePINVOKE.delete_TapAPIQuoteWhole(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public TapAPIContract Contract {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_Contract_set(swigCPtr, TapAPIContract.getCPtr(value));
    } 
    get {
      IntPtr cPtr = TapQuotePINVOKE.TapAPIQuoteWhole_Contract_get(swigCPtr);
      TapAPIContract ret = (cPtr == IntPtr.Zero) ? null : new TapAPIContract(cPtr, false);
      return ret;
    } 
  }

  public string CurrencyNo {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_CurrencyNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapQuotePINVOKE.TapAPIQuoteWhole_CurrencyNo_get(swigCPtr);
      return ret;
    } 
  }

  public char TradingState {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_TradingState_set(swigCPtr, value);
    } 
    get {
      char ret = TapQuotePINVOKE.TapAPIQuoteWhole_TradingState_get(swigCPtr);
      return ret;
    } 
  }

  public string DateTimeStamp {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_DateTimeStamp_set(swigCPtr, value);
    } 
    get {
      string ret = TapQuotePINVOKE.TapAPIQuoteWhole_DateTimeStamp_get(swigCPtr);
      return ret;
    } 
  }

  public double QPreClosingPrice {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QPreClosingPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIQuoteWhole_QPreClosingPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double QPreSettlePrice {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QPreSettlePrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIQuoteWhole_QPreSettlePrice_get(swigCPtr);
      return ret;
    } 
  }

  public ulong QPrePositionQty {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QPrePositionQty_set(swigCPtr, value);
    } 
    get {
      ulong ret = TapQuotePINVOKE.TapAPIQuoteWhole_QPrePositionQty_get(swigCPtr);
      return ret;
    } 
  }

  public double QOpeningPrice {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QOpeningPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIQuoteWhole_QOpeningPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double QLastPrice {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QLastPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIQuoteWhole_QLastPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double QHighPrice {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QHighPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIQuoteWhole_QHighPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double QLowPrice {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QLowPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIQuoteWhole_QLowPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double QHisHighPrice {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QHisHighPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIQuoteWhole_QHisHighPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double QHisLowPrice {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QHisLowPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIQuoteWhole_QHisLowPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double QLimitUpPrice {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QLimitUpPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIQuoteWhole_QLimitUpPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double QLimitDownPrice {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QLimitDownPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIQuoteWhole_QLimitDownPrice_get(swigCPtr);
      return ret;
    } 
  }

  public ulong QTotalQty {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QTotalQty_set(swigCPtr, value);
    } 
    get {
      ulong ret = TapQuotePINVOKE.TapAPIQuoteWhole_QTotalQty_get(swigCPtr);
      return ret;
    } 
  }

  public double QTotalTurnover {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QTotalTurnover_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIQuoteWhole_QTotalTurnover_get(swigCPtr);
      return ret;
    } 
  }

  public ulong QPositionQty {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QPositionQty_set(swigCPtr, value);
    } 
    get {
      ulong ret = TapQuotePINVOKE.TapAPIQuoteWhole_QPositionQty_get(swigCPtr);
      return ret;
    } 
  }

  public double QAveragePrice {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QAveragePrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIQuoteWhole_QAveragePrice_get(swigCPtr);
      return ret;
    } 
  }

  public double QClosingPrice {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QClosingPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIQuoteWhole_QClosingPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double QSettlePrice {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QSettlePrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIQuoteWhole_QSettlePrice_get(swigCPtr);
      return ret;
    } 
  }

  public ulong QLastQty {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QLastQty_set(swigCPtr, value);
    } 
    get {
      ulong ret = TapQuotePINVOKE.TapAPIQuoteWhole_QLastQty_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_double QBidPrice {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QBidPrice_set(swigCPtr, SWIGTYPE_p_double.getCPtr(value));
    } 
    get {
      IntPtr cPtr = TapQuotePINVOKE.TapAPIQuoteWhole_QBidPrice_get(swigCPtr);
      SWIGTYPE_p_double ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_unsigned_long_long QBidQty {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QBidQty_set(swigCPtr, SWIGTYPE_p_unsigned_long_long.getCPtr(value));
    } 
    get {
      IntPtr cPtr = TapQuotePINVOKE.TapAPIQuoteWhole_QBidQty_get(swigCPtr);
      SWIGTYPE_p_unsigned_long_long ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_long_long(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_double QAskPrice {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QAskPrice_set(swigCPtr, SWIGTYPE_p_double.getCPtr(value));
    } 
    get {
      IntPtr cPtr = TapQuotePINVOKE.TapAPIQuoteWhole_QAskPrice_get(swigCPtr);
      SWIGTYPE_p_double ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_unsigned_long_long QAskQty {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QAskQty_set(swigCPtr, SWIGTYPE_p_unsigned_long_long.getCPtr(value));
    } 
    get {
      IntPtr cPtr = TapQuotePINVOKE.TapAPIQuoteWhole_QAskQty_get(swigCPtr);
      SWIGTYPE_p_unsigned_long_long ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_long_long(cPtr, false);
      return ret;
    } 
  }

  public double QImpliedBidPrice {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QImpliedBidPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIQuoteWhole_QImpliedBidPrice_get(swigCPtr);
      return ret;
    } 
  }

  public ulong QImpliedBidQty {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QImpliedBidQty_set(swigCPtr, value);
    } 
    get {
      ulong ret = TapQuotePINVOKE.TapAPIQuoteWhole_QImpliedBidQty_get(swigCPtr);
      return ret;
    } 
  }

  public double QImpliedAskPrice {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QImpliedAskPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIQuoteWhole_QImpliedAskPrice_get(swigCPtr);
      return ret;
    } 
  }

  public ulong QImpliedAskQty {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QImpliedAskQty_set(swigCPtr, value);
    } 
    get {
      ulong ret = TapQuotePINVOKE.TapAPIQuoteWhole_QImpliedAskQty_get(swigCPtr);
      return ret;
    } 
  }

  public double QPreDelta {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QPreDelta_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIQuoteWhole_QPreDelta_get(swigCPtr);
      return ret;
    } 
  }

  public double QCurrDelta {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QCurrDelta_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIQuoteWhole_QCurrDelta_get(swigCPtr);
      return ret;
    } 
  }

  public ulong QInsideQty {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QInsideQty_set(swigCPtr, value);
    } 
    get {
      ulong ret = TapQuotePINVOKE.TapAPIQuoteWhole_QInsideQty_get(swigCPtr);
      return ret;
    } 
  }

  public ulong QOutsideQty {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QOutsideQty_set(swigCPtr, value);
    } 
    get {
      ulong ret = TapQuotePINVOKE.TapAPIQuoteWhole_QOutsideQty_get(swigCPtr);
      return ret;
    } 
  }

  public double QTurnoverRate {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QTurnoverRate_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIQuoteWhole_QTurnoverRate_get(swigCPtr);
      return ret;
    } 
  }

  public ulong Q5DAvgQty {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_Q5DAvgQty_set(swigCPtr, value);
    } 
    get {
      ulong ret = TapQuotePINVOKE.TapAPIQuoteWhole_Q5DAvgQty_get(swigCPtr);
      return ret;
    } 
  }

  public double QPERatio {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QPERatio_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIQuoteWhole_QPERatio_get(swigCPtr);
      return ret;
    } 
  }

  public double QTotalValue {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QTotalValue_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIQuoteWhole_QTotalValue_get(swigCPtr);
      return ret;
    } 
  }

  public double QNegotiableValue {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QNegotiableValue_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIQuoteWhole_QNegotiableValue_get(swigCPtr);
      return ret;
    } 
  }

  public long QPositionTrend {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QPositionTrend_set(swigCPtr, value);
    } 
    get {
      long ret = TapQuotePINVOKE.TapAPIQuoteWhole_QPositionTrend_get(swigCPtr);
      return ret;
    } 
  }

  public double QChangeSpeed {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QChangeSpeed_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIQuoteWhole_QChangeSpeed_get(swigCPtr);
      return ret;
    } 
  }

  public double QChangeRate {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QChangeRate_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIQuoteWhole_QChangeRate_get(swigCPtr);
      return ret;
    } 
  }

  public double QChangeValue {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QChangeValue_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIQuoteWhole_QChangeValue_get(swigCPtr);
      return ret;
    } 
  }

  public double QSwing {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QSwing_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIQuoteWhole_QSwing_get(swigCPtr);
      return ret;
    } 
  }

  public ulong QTotalBidQty {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QTotalBidQty_set(swigCPtr, value);
    } 
    get {
      ulong ret = TapQuotePINVOKE.TapAPIQuoteWhole_QTotalBidQty_get(swigCPtr);
      return ret;
    } 
  }

  public ulong QTotalAskQty {
    set {
      TapQuotePINVOKE.TapAPIQuoteWhole_QTotalAskQty_set(swigCPtr, value);
    } 
    get {
      ulong ret = TapQuotePINVOKE.TapAPIQuoteWhole_QTotalAskQty_get(swigCPtr);
      return ret;
    } 
  }

  public double GetQBidPrice(int pos) {
    double ret = TapQuotePINVOKE.TapAPIQuoteWhole_GetQBidPrice(swigCPtr, pos);
    return ret;
  }

  public ulong GetQBidQty(int pos) {
    ulong ret = TapQuotePINVOKE.TapAPIQuoteWhole_GetQBidQty(swigCPtr, pos);
    return ret;
  }

  public double GetQAskPrice(int pos) {
    double ret = TapQuotePINVOKE.TapAPIQuoteWhole_GetQAskPrice(swigCPtr, pos);
    return ret;
  }

  public ulong GetQAskQty(int pos) {
    ulong ret = TapQuotePINVOKE.TapAPIQuoteWhole_GetQAskQty(swigCPtr, pos);
    return ret;
  }

  public TapAPIQuoteWhole() : this(TapQuotePINVOKE.new_TapAPIQuoteWhole__SWIG_0(), true) {
  }

  public TapAPIQuoteWhole(TapAPIQuoteWhole other) : this(TapQuotePINVOKE.new_TapAPIQuoteWhole__SWIG_1(TapAPIQuoteWhole.getCPtr(other)), true) {
    if (TapQuotePINVOKE.SWIGPendingException.Pending) throw TapQuotePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
