/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace TapQuoteAPI {

using System;
using System.Runtime.InteropServices;

public class TapAPIHisQuote : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIHisQuote(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TapAPIHisQuote obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPIHisQuote() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapQuotePINVOKE.delete_TapAPIHisQuote(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public char HisQuoteType {
    set {
      TapQuotePINVOKE.TapAPIHisQuote_HisQuoteType_set(swigCPtr, value);
    } 
    get {
      char ret = TapQuotePINVOKE.TapAPIHisQuote_HisQuoteType_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIContract Contract {
    set {
      TapQuotePINVOKE.TapAPIHisQuote_Contract_set(swigCPtr, TapAPIContract.getCPtr(value));
    } 
    get {
      IntPtr cPtr = TapQuotePINVOKE.TapAPIHisQuote_Contract_get(swigCPtr);
      TapAPIContract ret = (cPtr == IntPtr.Zero) ? null : new TapAPIContract(cPtr, false);
      return ret;
    } 
  }

  public string DateTimeStamp {
    set {
      TapQuotePINVOKE.TapAPIHisQuote_DateTimeStamp_set(swigCPtr, value);
    } 
    get {
      string ret = TapQuotePINVOKE.TapAPIHisQuote_DateTimeStamp_get(swigCPtr);
      return ret;
    } 
  }

  public string TradeDate {
    set {
      TapQuotePINVOKE.TapAPIHisQuote_TradeDate_set(swigCPtr, value);
    } 
    get {
      string ret = TapQuotePINVOKE.TapAPIHisQuote_TradeDate_get(swigCPtr);
      return ret;
    } 
  }

  public uint KLineIndex {
    set {
      TapQuotePINVOKE.TapAPIHisQuote_KLineIndex_set(swigCPtr, value);
    } 
    get {
      uint ret = TapQuotePINVOKE.TapAPIHisQuote_KLineIndex_get(swigCPtr);
      return ret;
    } 
  }

  public double QOpeningPrice {
    set {
      TapQuotePINVOKE.TapAPIHisQuote_QOpeningPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIHisQuote_QOpeningPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double QLastPrice {
    set {
      TapQuotePINVOKE.TapAPIHisQuote_QLastPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIHisQuote_QLastPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double QHighPrice {
    set {
      TapQuotePINVOKE.TapAPIHisQuote_QHighPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIHisQuote_QHighPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double QLowPrice {
    set {
      TapQuotePINVOKE.TapAPIHisQuote_QLowPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIHisQuote_QLowPrice_get(swigCPtr);
      return ret;
    } 
  }

  public ulong QTotalQty {
    set {
      TapQuotePINVOKE.TapAPIHisQuote_QTotalQty_set(swigCPtr, value);
    } 
    get {
      ulong ret = TapQuotePINVOKE.TapAPIHisQuote_QTotalQty_get(swigCPtr);
      return ret;
    } 
  }

  public ulong QPositionQty {
    set {
      TapQuotePINVOKE.TapAPIHisQuote_QPositionQty_set(swigCPtr, value);
    } 
    get {
      ulong ret = TapQuotePINVOKE.TapAPIHisQuote_QPositionQty_get(swigCPtr);
      return ret;
    } 
  }

  public double QSettlePrice {
    set {
      TapQuotePINVOKE.TapAPIHisQuote_QSettlePrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIHisQuote_QSettlePrice_get(swigCPtr);
      return ret;
    } 
  }

  public ulong QKLineTotalQty {
    set {
      TapQuotePINVOKE.TapAPIHisQuote_QKLineTotalQty_set(swigCPtr, value);
    } 
    get {
      ulong ret = TapQuotePINVOKE.TapAPIHisQuote_QKLineTotalQty_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIHisQuote() : this(TapQuotePINVOKE.new_TapAPIHisQuote__SWIG_0(), true) {
  }

  public TapAPIHisQuote(TapAPIHisQuote other) : this(TapQuotePINVOKE.new_TapAPIHisQuote__SWIG_1(TapAPIHisQuote.getCPtr(other)), true) {
    if (TapQuotePINVOKE.SWIGPendingException.Pending) throw TapQuotePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
