/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace TapQuoteAPI {

using System;
using System.Runtime.InteropServices;

public class TapAPIHisQuoteQryRsp : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIHisQuoteQryRsp(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TapAPIHisQuoteQryRsp obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPIHisQuoteQryRsp() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapQuotePINVOKE.delete_TapAPIHisQuoteQryRsp(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public uint Count {
    set {
      TapQuotePINVOKE.TapAPIHisQuoteQryRsp_Count_set(swigCPtr, value);
    } 
    get {
      uint ret = TapQuotePINVOKE.TapAPIHisQuoteQryRsp_Count_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIHisQuote HisQuotes {
    set {
      TapQuotePINVOKE.TapAPIHisQuoteQryRsp_HisQuotes_set(swigCPtr, TapAPIHisQuote.getCPtr(value));
    } 
    get {
      IntPtr cPtr = TapQuotePINVOKE.TapAPIHisQuoteQryRsp_HisQuotes_get(swigCPtr);
      TapAPIHisQuote ret = (cPtr == IntPtr.Zero) ? null : new TapAPIHisQuote(cPtr, false);
      return ret;
    } 
  }

  public TapAPIHisQuoteQryRsp() : this(TapQuotePINVOKE.new_TapAPIHisQuoteQryRsp__SWIG_0(), true) {
  }

  public TapAPIHisQuoteQryRsp(TapAPIHisQuoteQryRsp other) : this(TapQuotePINVOKE.new_TapAPIHisQuoteQryRsp__SWIG_1(TapAPIHisQuoteQryRsp.getCPtr(other)), true) {
    if (TapQuotePINVOKE.SWIGPendingException.Pending) throw TapQuotePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
