/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace TapQuoteAPI {

using System;
using System.Runtime.InteropServices;

public class TapAPIQuoteLoginAuth : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIQuoteLoginAuth(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TapAPIQuoteLoginAuth obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPIQuoteLoginAuth() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapQuotePINVOKE.delete_TapAPIQuoteLoginAuth(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public string UserNo {
    set {
      TapQuotePINVOKE.TapAPIQuoteLoginAuth_UserNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapQuotePINVOKE.TapAPIQuoteLoginAuth_UserNo_get(swigCPtr);
      return ret;
    } 
  }

  public char ISModifyPassword {
    set {
      TapQuotePINVOKE.TapAPIQuoteLoginAuth_ISModifyPassword_set(swigCPtr, value);
    } 
    get {
      char ret = TapQuotePINVOKE.TapAPIQuoteLoginAuth_ISModifyPassword_get(swigCPtr);
      return ret;
    } 
  }

  public string Password {
    set {
      TapQuotePINVOKE.TapAPIQuoteLoginAuth_Password_set(swigCPtr, value);
    } 
    get {
      string ret = TapQuotePINVOKE.TapAPIQuoteLoginAuth_Password_get(swigCPtr);
      return ret;
    } 
  }

  public string NewPassword {
    set {
      TapQuotePINVOKE.TapAPIQuoteLoginAuth_NewPassword_set(swigCPtr, value);
    } 
    get {
      string ret = TapQuotePINVOKE.TapAPIQuoteLoginAuth_NewPassword_get(swigCPtr);
      return ret;
    } 
  }

  public string QuoteTempPassword {
    set {
      TapQuotePINVOKE.TapAPIQuoteLoginAuth_QuoteTempPassword_set(swigCPtr, value);
    } 
    get {
      string ret = TapQuotePINVOKE.TapAPIQuoteLoginAuth_QuoteTempPassword_get(swigCPtr);
      return ret;
    } 
  }

  public char ISDDA {
    set {
      TapQuotePINVOKE.TapAPIQuoteLoginAuth_ISDDA_set(swigCPtr, value);
    } 
    get {
      char ret = TapQuotePINVOKE.TapAPIQuoteLoginAuth_ISDDA_get(swigCPtr);
      return ret;
    } 
  }

  public string DDASerialNo {
    set {
      TapQuotePINVOKE.TapAPIQuoteLoginAuth_DDASerialNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapQuotePINVOKE.TapAPIQuoteLoginAuth_DDASerialNo_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIQuoteLoginAuth() : this(TapQuotePINVOKE.new_TapAPIQuoteLoginAuth__SWIG_0(), true) {
  }

  public TapAPIQuoteLoginAuth(TapAPIQuoteLoginAuth other) : this(TapQuotePINVOKE.new_TapAPIQuoteLoginAuth__SWIG_1(TapAPIQuoteLoginAuth.getCPtr(other)), true) {
    if (TapQuotePINVOKE.SWIGPendingException.Pending) throw TapQuotePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
