/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace TapQuoteAPI {

using System;
using System.Runtime.InteropServices;

public class TapAPITradingTimeBucket : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPITradingTimeBucket(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TapAPITradingTimeBucket obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPITradingTimeBucket() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapQuotePINVOKE.delete_TapAPITradingTimeBucket(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public int TradingTimeBucketID {
    set {
      TapQuotePINVOKE.TapAPITradingTimeBucket_TradingTimeBucketID_set(swigCPtr, value);
    } 
    get {
      int ret = TapQuotePINVOKE.TapAPITradingTimeBucket_TradingTimeBucketID_get(swigCPtr);
      return ret;
    } 
  }

  public string TimeBucketBeginTime {
    set {
      TapQuotePINVOKE.TapAPITradingTimeBucket_TimeBucketBeginTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapQuotePINVOKE.TapAPITradingTimeBucket_TimeBucketBeginTime_get(swigCPtr);
      return ret;
    } 
  }

  public char TradingState {
    set {
      TapQuotePINVOKE.TapAPITradingTimeBucket_TradingState_set(swigCPtr, value);
    } 
    get {
      char ret = TapQuotePINVOKE.TapAPITradingTimeBucket_TradingState_get(swigCPtr);
      return ret;
    } 
  }

  public char IsDST {
    set {
      TapQuotePINVOKE.TapAPITradingTimeBucket_IsDST_set(swigCPtr, value);
    } 
    get {
      char ret = TapQuotePINVOKE.TapAPITradingTimeBucket_IsDST_get(swigCPtr);
      return ret;
    } 
  }

  public char DateFlag {
    set {
      TapQuotePINVOKE.TapAPITradingTimeBucket_DateFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapQuotePINVOKE.TapAPITradingTimeBucket_DateFlag_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPITradingTimeBucket() : this(TapQuotePINVOKE.new_TapAPITradingTimeBucket__SWIG_0(), true) {
  }

  public TapAPITradingTimeBucket(TapAPITradingTimeBucket other) : this(TapQuotePINVOKE.new_TapAPITradingTimeBucket__SWIG_1(TapAPITradingTimeBucket.getCPtr(other)), true) {
    if (TapQuotePINVOKE.SWIGPendingException.Pending) throw TapQuotePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
