/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace TapQuoteAPI {

using System;
using System.Runtime.InteropServices;

public class TapAPIQuoteCommodityInfo : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIQuoteCommodityInfo(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TapAPIQuoteCommodityInfo obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPIQuoteCommodityInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapQuotePINVOKE.delete_TapAPIQuoteCommodityInfo(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public TapAPICommodity Commodity {
    set {
      TapQuotePINVOKE.TapAPIQuoteCommodityInfo_Commodity_set(swigCPtr, TapAPICommodity.getCPtr(value));
    } 
    get {
      IntPtr cPtr = TapQuotePINVOKE.TapAPIQuoteCommodityInfo_Commodity_get(swigCPtr);
      TapAPICommodity ret = (cPtr == IntPtr.Zero) ? null : new TapAPICommodity(cPtr, false);
      return ret;
    } 
  }

  public string CommodityName {
    set {
      TapQuotePINVOKE.TapAPIQuoteCommodityInfo_CommodityName_set(swigCPtr, value);
    } 
    get {
      string ret = TapQuotePINVOKE.TapAPIQuoteCommodityInfo_CommodityName_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityEngName {
    set {
      TapQuotePINVOKE.TapAPIQuoteCommodityInfo_CommodityEngName_set(swigCPtr, value);
    } 
    get {
      string ret = TapQuotePINVOKE.TapAPIQuoteCommodityInfo_CommodityEngName_get(swigCPtr);
      return ret;
    } 
  }

  public double ContractSize {
    set {
      TapQuotePINVOKE.TapAPIQuoteCommodityInfo_ContractSize_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIQuoteCommodityInfo_ContractSize_get(swigCPtr);
      return ret;
    } 
  }

  public double CommodityTickSize {
    set {
      TapQuotePINVOKE.TapAPIQuoteCommodityInfo_CommodityTickSize_set(swigCPtr, value);
    } 
    get {
      double ret = TapQuotePINVOKE.TapAPIQuoteCommodityInfo_CommodityTickSize_get(swigCPtr);
      return ret;
    } 
  }

  public int CommodityDenominator {
    set {
      TapQuotePINVOKE.TapAPIQuoteCommodityInfo_CommodityDenominator_set(swigCPtr, value);
    } 
    get {
      int ret = TapQuotePINVOKE.TapAPIQuoteCommodityInfo_CommodityDenominator_get(swigCPtr);
      return ret;
    } 
  }

  public char CmbDirect {
    set {
      TapQuotePINVOKE.TapAPIQuoteCommodityInfo_CmbDirect_set(swigCPtr, value);
    } 
    get {
      char ret = TapQuotePINVOKE.TapAPIQuoteCommodityInfo_CmbDirect_get(swigCPtr);
      return ret;
    } 
  }

  public int CommodityContractLen {
    set {
      TapQuotePINVOKE.TapAPIQuoteCommodityInfo_CommodityContractLen_set(swigCPtr, value);
    } 
    get {
      int ret = TapQuotePINVOKE.TapAPIQuoteCommodityInfo_CommodityContractLen_get(swigCPtr);
      return ret;
    } 
  }

  public char IsDST {
    set {
      TapQuotePINVOKE.TapAPIQuoteCommodityInfo_IsDST_set(swigCPtr, value);
    } 
    get {
      char ret = TapQuotePINVOKE.TapAPIQuoteCommodityInfo_IsDST_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPICommodity RelateCommodity1 {
    set {
      TapQuotePINVOKE.TapAPIQuoteCommodityInfo_RelateCommodity1_set(swigCPtr, TapAPICommodity.getCPtr(value));
    } 
    get {
      IntPtr cPtr = TapQuotePINVOKE.TapAPIQuoteCommodityInfo_RelateCommodity1_get(swigCPtr);
      TapAPICommodity ret = (cPtr == IntPtr.Zero) ? null : new TapAPICommodity(cPtr, false);
      return ret;
    } 
  }

  public TapAPICommodity RelateCommodity2 {
    set {
      TapQuotePINVOKE.TapAPIQuoteCommodityInfo_RelateCommodity2_set(swigCPtr, TapAPICommodity.getCPtr(value));
    } 
    get {
      IntPtr cPtr = TapQuotePINVOKE.TapAPIQuoteCommodityInfo_RelateCommodity2_get(swigCPtr);
      TapAPICommodity ret = (cPtr == IntPtr.Zero) ? null : new TapAPICommodity(cPtr, false);
      return ret;
    } 
  }

  public TapAPIQuoteCommodityInfo() : this(TapQuotePINVOKE.new_TapAPIQuoteCommodityInfo__SWIG_0(), true) {
  }

  public TapAPIQuoteCommodityInfo(TapAPIQuoteCommodityInfo other) : this(TapQuotePINVOKE.new_TapAPIQuoteCommodityInfo__SWIG_1(TapAPIQuoteCommodityInfo.getCPtr(other)), true) {
    if (TapQuotePINVOKE.SWIGPendingException.Pending) throw TapQuotePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
