/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace TapQuoteAPI {

using System;
using System.Runtime.InteropServices;

public class TapAPITimeBucketOfCommodityInfo : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPITimeBucketOfCommodityInfo(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TapAPITimeBucketOfCommodityInfo obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPITimeBucketOfCommodityInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapQuotePINVOKE.delete_TapAPITimeBucketOfCommodityInfo(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public TapAPICommodity Commodity {
    set {
      TapQuotePINVOKE.TapAPITimeBucketOfCommodityInfo_Commodity_set(swigCPtr, TapAPICommodity.getCPtr(value));
    } 
    get {
      IntPtr cPtr = TapQuotePINVOKE.TapAPITimeBucketOfCommodityInfo_Commodity_get(swigCPtr);
      TapAPICommodity ret = (cPtr == IntPtr.Zero) ? null : new TapAPICommodity(cPtr, false);
      return ret;
    } 
  }

  public uint Count {
    set {
      TapQuotePINVOKE.TapAPITimeBucketOfCommodityInfo_Count_set(swigCPtr, value);
    } 
    get {
      uint ret = TapQuotePINVOKE.TapAPITimeBucketOfCommodityInfo_Count_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPITradingTimeBucket TimeBuckets {
    set {
      TapQuotePINVOKE.TapAPITimeBucketOfCommodityInfo_TimeBuckets_set(swigCPtr, TapAPITradingTimeBucket.getCPtr(value));
    } 
    get {
      IntPtr cPtr = TapQuotePINVOKE.TapAPITimeBucketOfCommodityInfo_TimeBuckets_get(swigCPtr);
      TapAPITradingTimeBucket ret = (cPtr == IntPtr.Zero) ? null : new TapAPITradingTimeBucket(cPtr, false);
      return ret;
    } 
  }

  public TapAPITimeBucketOfCommodityInfo() : this(TapQuotePINVOKE.new_TapAPITimeBucketOfCommodityInfo__SWIG_0(), true) {
  }

  public TapAPITimeBucketOfCommodityInfo(TapAPITimeBucketOfCommodityInfo other) : this(TapQuotePINVOKE.new_TapAPITimeBucketOfCommodityInfo__SWIG_1(TapAPITimeBucketOfCommodityInfo.getCPtr(other)), true) {
    if (TapQuotePINVOKE.SWIGPendingException.Pending) throw TapQuotePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
