/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace TapQuoteAPI {

using System;
using System.Runtime.InteropServices;

public class TapAPIExchangeInfo : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIExchangeInfo(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TapAPIExchangeInfo obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPIExchangeInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapQuotePINVOKE.delete_TapAPIExchangeInfo(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public string ExchangeNo {
    set {
      TapQuotePINVOKE.TapAPIExchangeInfo_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapQuotePINVOKE.TapAPIExchangeInfo_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeName {
    set {
      TapQuotePINVOKE.TapAPIExchangeInfo_ExchangeName_set(swigCPtr, value);
    } 
    get {
      string ret = TapQuotePINVOKE.TapAPIExchangeInfo_ExchangeName_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIExchangeInfo() : this(TapQuotePINVOKE.new_TapAPIExchangeInfo__SWIG_0(), true) {
  }

  public TapAPIExchangeInfo(TapAPIExchangeInfo other) : this(TapQuotePINVOKE.new_TapAPIExchangeInfo__SWIG_1(TapAPIExchangeInfo.getCPtr(other)), true) {
    if (TapQuotePINVOKE.SWIGPendingException.Pending) throw TapQuotePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
