/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace TapTradeAPI {

using System;
using System.Runtime.InteropServices;

public class ITapTradeAPI : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ITapTradeAPI(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ITapTradeAPI obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ITapTradeAPI() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradePINVOKE.delete_ITapTradeAPI(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public virtual int SetAPINotify(ITapTradeAPINotify apiNotify) {
    int ret = TapTradePINVOKE.ITapTradeAPI_SetAPINotify(swigCPtr, ITapTradeAPINotify.getCPtr(apiNotify));
    return ret;
  }

  public virtual int SetHostAddress(string IP, ushort port) {
    int ret = TapTradePINVOKE.ITapTradeAPI_SetHostAddress(swigCPtr, IP, port);
    return ret;
  }

  public virtual int Login(TapAPITradeLoginAuth loginAuth) {
    int ret = TapTradePINVOKE.ITapTradeAPI_Login(swigCPtr, TapAPITradeLoginAuth.getCPtr(loginAuth));
    return ret;
  }

  public virtual int Disconnect() {
    int ret = TapTradePINVOKE.ITapTradeAPI_Disconnect(swigCPtr);
    return ret;
  }

  public virtual int ChangePassword(out uint sessionID, TapAPIChangePasswordReq req) {
    int ret = TapTradePINVOKE.ITapTradeAPI_ChangePassword(swigCPtr, out sessionID, TapAPIChangePasswordReq.getCPtr(req));
    return ret;
  }

  public virtual int HaveCertainRight(int rightID) {
    int ret = TapTradePINVOKE.ITapTradeAPI_HaveCertainRight(swigCPtr, rightID);
    return ret;
  }

  public virtual int SetReservedInfo(out uint sessionID, string info) {
    int ret = TapTradePINVOKE.ITapTradeAPI_SetReservedInfo(swigCPtr, out sessionID, info);
    return ret;
  }

  public virtual int QryAccount(out uint sessionID, TapAPIAccQryReq qryReq) {
    int ret = TapTradePINVOKE.ITapTradeAPI_QryAccount(swigCPtr, out sessionID, TapAPIAccQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryFund(out uint sessionID, TapAPIFundReq qryReq) {
    int ret = TapTradePINVOKE.ITapTradeAPI_QryFund(swigCPtr, out sessionID, TapAPIFundReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryExchange(out uint sessionID) {
    int ret = TapTradePINVOKE.ITapTradeAPI_QryExchange(swigCPtr, out sessionID);
    return ret;
  }

  public virtual int QryCommodity(out uint sessionID) {
    int ret = TapTradePINVOKE.ITapTradeAPI_QryCommodity(swigCPtr, out sessionID);
    return ret;
  }

  public virtual int QryContract(out uint sessionID, TapAPICommodity qryReq) {
    int ret = TapTradePINVOKE.ITapTradeAPI_QryContract(swigCPtr, out sessionID, TapAPICommodity.getCPtr(qryReq));
    return ret;
  }

  public virtual int InsertOrder(out uint sessionID, TapAPINewOrder order) {
    int ret = TapTradePINVOKE.ITapTradeAPI_InsertOrder(swigCPtr, out sessionID, TapAPINewOrder.getCPtr(order));
    return ret;
  }

  public virtual int CancelOrder(out uint sessionID, TapAPIOrderCancelReq order) {
    int ret = TapTradePINVOKE.ITapTradeAPI_CancelOrder(swigCPtr, out sessionID, TapAPIOrderCancelReq.getCPtr(order));
    return ret;
  }

  public virtual int QryOrder(out uint sessionID, TapAPIOrderQryReq qryReq) {
    int ret = TapTradePINVOKE.ITapTradeAPI_QryOrder(swigCPtr, out sessionID, TapAPIOrderQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryOrderProcess(out uint sessionID, TapAPIOrderProcessQryReq qryReq) {
    int ret = TapTradePINVOKE.ITapTradeAPI_QryOrderProcess(swigCPtr, out sessionID, TapAPIOrderProcessQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryFill(out uint sessionID, TapAPIOrderQryReq qryReq) {
    int ret = TapTradePINVOKE.ITapTradeAPI_QryFill(swigCPtr, out sessionID, TapAPIOrderQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryPosition(out uint sessionID, TapAPICloseQryReq qryReq) {
    int ret = TapTradePINVOKE.ITapTradeAPI_QryPosition(swigCPtr, out sessionID, TapAPICloseQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryClose(out uint sessionID, TapAPICloseQryReq qryReq) {
    int ret = TapTradePINVOKE.ITapTradeAPI_QryClose(swigCPtr, out sessionID, TapAPICloseQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryDeepQuote(out uint sessionID, TapAPIContract qryReq) {
    int ret = TapTradePINVOKE.ITapTradeAPI_QryDeepQuote(swigCPtr, out sessionID, TapAPIContract.getCPtr(qryReq));
    return ret;
  }

}

}
