/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace TapTradeAPI {

using System;
using System.Runtime.InteropServices;

public class TapAPIAccountInfo : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIAccountInfo(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TapAPIAccountInfo obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPIAccountInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradePINVOKE.delete_TapAPIAccountInfo(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public string AccountNo {
    set {
      TapTradePINVOKE.TapAPIAccountInfo_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIAccountInfo_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public char AccountType {
    set {
      TapTradePINVOKE.TapAPIAccountInfo_AccountType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIAccountInfo_AccountType_get(swigCPtr);
      return ret;
    } 
  }

  public char AccountState {
    set {
      TapTradePINVOKE.TapAPIAccountInfo_AccountState_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIAccountInfo_AccountState_get(swigCPtr);
      return ret;
    } 
  }

  public string AccountShortName {
    set {
      TapTradePINVOKE.TapAPIAccountInfo_AccountShortName_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIAccountInfo_AccountShortName_get(swigCPtr);
      return ret;
    } 
  }

  public char AccountIsDocHolder {
    set {
      TapTradePINVOKE.TapAPIAccountInfo_AccountIsDocHolder_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIAccountInfo_AccountIsDocHolder_get(swigCPtr);
      return ret;
    } 
  }

  public char IsMarketMaker {
    set {
      TapTradePINVOKE.TapAPIAccountInfo_IsMarketMaker_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIAccountInfo_IsMarketMaker_get(swigCPtr);
      return ret;
    } 
  }

  public char AccountFamilyType {
    set {
      TapTradePINVOKE.TapAPIAccountInfo_AccountFamilyType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIAccountInfo_AccountFamilyType_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIAccountInfo() : this(TapTradePINVOKE.new_TapAPIAccountInfo__SWIG_0(), true) {
  }

  public TapAPIAccountInfo(TapAPIAccountInfo other) : this(TapTradePINVOKE.new_TapAPIAccountInfo__SWIG_1(TapAPIAccountInfo.getCPtr(other)), true) {
    if (TapTradePINVOKE.SWIGPendingException.Pending) throw TapTradePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
