/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace TapTradeAPI {

using System;
using System.Runtime.InteropServices;

public class TapAPIDeepQuoteQryRsp : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIDeepQuoteQryRsp(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TapAPIDeepQuoteQryRsp obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPIDeepQuoteQryRsp() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradePINVOKE.delete_TapAPIDeepQuoteQryRsp(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public TapAPIContract Contract {
    set {
      TapTradePINVOKE.TapAPIDeepQuoteQryRsp_Contract_set(swigCPtr, TapAPIContract.getCPtr(value));
    } 
    get {
      IntPtr cPtr = TapTradePINVOKE.TapAPIDeepQuoteQryRsp_Contract_get(swigCPtr);
      TapAPIContract ret = (cPtr == IntPtr.Zero) ? null : new TapAPIContract(cPtr, false);
      return ret;
    } 
  }

  public TapAPIDeepQuoteInfo DeepQuote {
    set {
      TapTradePINVOKE.TapAPIDeepQuoteQryRsp_DeepQuote_set(swigCPtr, TapAPIDeepQuoteInfo.getCPtr(value));
    } 
    get {
      IntPtr cPtr = TapTradePINVOKE.TapAPIDeepQuoteQryRsp_DeepQuote_get(swigCPtr);
      TapAPIDeepQuoteInfo ret = (cPtr == IntPtr.Zero) ? null : new TapAPIDeepQuoteInfo(cPtr, false);
      return ret;
    } 
  }

  public TapAPIDeepQuoteQryRsp() : this(TapTradePINVOKE.new_TapAPIDeepQuoteQryRsp__SWIG_0(), true) {
  }

  public TapAPIDeepQuoteQryRsp(TapAPIDeepQuoteQryRsp other) : this(TapTradePINVOKE.new_TapAPIDeepQuoteQryRsp__SWIG_1(TapAPIDeepQuoteQryRsp.getCPtr(other)), true) {
    if (TapTradePINVOKE.SWIGPendingException.Pending) throw TapTradePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
