/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace TapTradeAPI {

using System;
using System.Runtime.InteropServices;

public class TapAPIFillInfo : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIFillInfo(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TapAPIFillInfo obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPIFillInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradePINVOKE.delete_TapAPIFillInfo(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public string AccountNo {
    set {
      TapTradePINVOKE.TapAPIFillInfo_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIFillInfo_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ParentAccountNo {
    set {
      TapTradePINVOKE.TapAPIFillInfo_ParentAccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIFillInfo_ParentAccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      TapTradePINVOKE.TapAPIFillInfo_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIFillInfo_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityType {
    set {
      TapTradePINVOKE.TapAPIFillInfo_CommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIFillInfo_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      TapTradePINVOKE.TapAPIFillInfo_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIFillInfo_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo {
    set {
      TapTradePINVOKE.TapAPIFillInfo_ContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIFillInfo_ContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice {
    set {
      TapTradePINVOKE.TapAPIFillInfo_StrikePrice_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIFillInfo_StrikePrice_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag {
    set {
      TapTradePINVOKE.TapAPIFillInfo_CallOrPutFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIFillInfo_CallOrPutFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNoRef {
    set {
      TapTradePINVOKE.TapAPIFillInfo_ExchangeNoRef_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIFillInfo_ExchangeNoRef_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityTypeRef {
    set {
      TapTradePINVOKE.TapAPIFillInfo_CommodityTypeRef_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIFillInfo_CommodityTypeRef_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNoRef {
    set {
      TapTradePINVOKE.TapAPIFillInfo_CommodityNoRef_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIFillInfo_CommodityNoRef_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNoRef {
    set {
      TapTradePINVOKE.TapAPIFillInfo_ContractNoRef_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIFillInfo_ContractNoRef_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePriceRef {
    set {
      TapTradePINVOKE.TapAPIFillInfo_StrikePriceRef_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIFillInfo_StrikePriceRef_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlagRef {
    set {
      TapTradePINVOKE.TapAPIFillInfo_CallOrPutFlagRef_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIFillInfo_CallOrPutFlagRef_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderExchangeNo {
    set {
      TapTradePINVOKE.TapAPIFillInfo_OrderExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIFillInfo_OrderExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderCommodityType {
    set {
      TapTradePINVOKE.TapAPIFillInfo_OrderCommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIFillInfo_OrderCommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderCommodityNo {
    set {
      TapTradePINVOKE.TapAPIFillInfo_OrderCommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIFillInfo_OrderCommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderType {
    set {
      TapTradePINVOKE.TapAPIFillInfo_OrderType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIFillInfo_OrderType_get(swigCPtr);
      return ret;
    } 
  }

  public char MatchSource {
    set {
      TapTradePINVOKE.TapAPIFillInfo_MatchSource_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIFillInfo_MatchSource_get(swigCPtr);
      return ret;
    } 
  }

  public char TimeInForce {
    set {
      TapTradePINVOKE.TapAPIFillInfo_TimeInForce_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIFillInfo_TimeInForce_get(swigCPtr);
      return ret;
    } 
  }

  public string ExpireTime {
    set {
      TapTradePINVOKE.TapAPIFillInfo_ExpireTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIFillInfo_ExpireTime_get(swigCPtr);
      return ret;
    } 
  }

  public char IsRiskOrder {
    set {
      TapTradePINVOKE.TapAPIFillInfo_IsRiskOrder_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIFillInfo_IsRiskOrder_get(swigCPtr);
      return ret;
    } 
  }

  public char MatchSide {
    set {
      TapTradePINVOKE.TapAPIFillInfo_MatchSide_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIFillInfo_MatchSide_get(swigCPtr);
      return ret;
    } 
  }

  public char PositionEffect {
    set {
      TapTradePINVOKE.TapAPIFillInfo_PositionEffect_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIFillInfo_PositionEffect_get(swigCPtr);
      return ret;
    } 
  }

  public char PositionEffectRef {
    set {
      TapTradePINVOKE.TapAPIFillInfo_PositionEffectRef_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIFillInfo_PositionEffectRef_get(swigCPtr);
      return ret;
    } 
  }

  public char HedgeFlag {
    set {
      TapTradePINVOKE.TapAPIFillInfo_HedgeFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIFillInfo_HedgeFlag_get(swigCPtr);
      return ret;
    } 
  }

  public char ServerFlag {
    set {
      TapTradePINVOKE.TapAPIFillInfo_ServerFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIFillInfo_ServerFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderNo {
    set {
      TapTradePINVOKE.TapAPIFillInfo_OrderNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIFillInfo_OrderNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderLocalNo {
    set {
      TapTradePINVOKE.TapAPIFillInfo_OrderLocalNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIFillInfo_OrderLocalNo_get(swigCPtr);
      return ret;
    } 
  }

  public string MatchNo {
    set {
      TapTradePINVOKE.TapAPIFillInfo_MatchNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIFillInfo_MatchNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeMatchNo {
    set {
      TapTradePINVOKE.TapAPIFillInfo_ExchangeMatchNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIFillInfo_ExchangeMatchNo_get(swigCPtr);
      return ret;
    } 
  }

  public string MatchDateTime {
    set {
      TapTradePINVOKE.TapAPIFillInfo_MatchDateTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIFillInfo_MatchDateTime_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperMatchDateTime {
    set {
      TapTradePINVOKE.TapAPIFillInfo_UpperMatchDateTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIFillInfo_UpperMatchDateTime_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperNo {
    set {
      TapTradePINVOKE.TapAPIFillInfo_UpperNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIFillInfo_UpperNo_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperChannelNo {
    set {
      TapTradePINVOKE.TapAPIFillInfo_UpperChannelNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIFillInfo_UpperChannelNo_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperSettleNo {
    set {
      TapTradePINVOKE.TapAPIFillInfo_UpperSettleNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIFillInfo_UpperSettleNo_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperUserNo {
    set {
      TapTradePINVOKE.TapAPIFillInfo_UpperUserNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIFillInfo_UpperUserNo_get(swigCPtr);
      return ret;
    } 
  }

  public string TradeNo {
    set {
      TapTradePINVOKE.TapAPIFillInfo_TradeNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIFillInfo_TradeNo_get(swigCPtr);
      return ret;
    } 
  }

  public double MatchPrice {
    set {
      TapTradePINVOKE.TapAPIFillInfo_MatchPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIFillInfo_MatchPrice_get(swigCPtr);
      return ret;
    } 
  }

  public uint MatchQty {
    set {
      TapTradePINVOKE.TapAPIFillInfo_MatchQty_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradePINVOKE.TapAPIFillInfo_MatchQty_get(swigCPtr);
      return ret;
    } 
  }

  public char IsBackInput {
    set {
      TapTradePINVOKE.TapAPIFillInfo_IsBackInput_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIFillInfo_IsBackInput_get(swigCPtr);
      return ret;
    } 
  }

  public char IsDeleted {
    set {
      TapTradePINVOKE.TapAPIFillInfo_IsDeleted_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIFillInfo_IsDeleted_get(swigCPtr);
      return ret;
    } 
  }

  public char IsAddOne {
    set {
      TapTradePINVOKE.TapAPIFillInfo_IsAddOne_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIFillInfo_IsAddOne_get(swigCPtr);
      return ret;
    } 
  }

  public uint MatchStreamID {
    set {
      TapTradePINVOKE.TapAPIFillInfo_MatchStreamID_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradePINVOKE.TapAPIFillInfo_MatchStreamID_get(swigCPtr);
      return ret;
    } 
  }

  public uint UpperStreamID {
    set {
      TapTradePINVOKE.TapAPIFillInfo_UpperStreamID_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradePINVOKE.TapAPIFillInfo_UpperStreamID_get(swigCPtr);
      return ret;
    } 
  }

  public char OpenCloseMode {
    set {
      TapTradePINVOKE.TapAPIFillInfo_OpenCloseMode_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIFillInfo_OpenCloseMode_get(swigCPtr);
      return ret;
    } 
  }

  public double ContractSize {
    set {
      TapTradePINVOKE.TapAPIFillInfo_ContractSize_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIFillInfo_ContractSize_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityCurrencyGroup {
    set {
      TapTradePINVOKE.TapAPIFillInfo_CommodityCurrencyGroup_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIFillInfo_CommodityCurrencyGroup_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityCurrency {
    set {
      TapTradePINVOKE.TapAPIFillInfo_CommodityCurrency_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIFillInfo_CommodityCurrency_get(swigCPtr);
      return ret;
    } 
  }

  public char FeeMode {
    set {
      TapTradePINVOKE.TapAPIFillInfo_FeeMode_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIFillInfo_FeeMode_get(swigCPtr);
      return ret;
    } 
  }

  public double FeeParam {
    set {
      TapTradePINVOKE.TapAPIFillInfo_FeeParam_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIFillInfo_FeeParam_get(swigCPtr);
      return ret;
    } 
  }

  public string FeeCurrencyGroup {
    set {
      TapTradePINVOKE.TapAPIFillInfo_FeeCurrencyGroup_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIFillInfo_FeeCurrencyGroup_get(swigCPtr);
      return ret;
    } 
  }

  public string FeeCurrency {
    set {
      TapTradePINVOKE.TapAPIFillInfo_FeeCurrency_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIFillInfo_FeeCurrency_get(swigCPtr);
      return ret;
    } 
  }

  public double PreSettlePrice {
    set {
      TapTradePINVOKE.TapAPIFillInfo_PreSettlePrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIFillInfo_PreSettlePrice_get(swigCPtr);
      return ret;
    } 
  }

  public double FeeValue {
    set {
      TapTradePINVOKE.TapAPIFillInfo_FeeValue_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIFillInfo_FeeValue_get(swigCPtr);
      return ret;
    } 
  }

  public char IsManualFee {
    set {
      TapTradePINVOKE.TapAPIFillInfo_IsManualFee_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIFillInfo_IsManualFee_get(swigCPtr);
      return ret;
    } 
  }

  public double Turnover {
    set {
      TapTradePINVOKE.TapAPIFillInfo_Turnover_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIFillInfo_Turnover_get(swigCPtr);
      return ret;
    } 
  }

  public double PremiumIncome {
    set {
      TapTradePINVOKE.TapAPIFillInfo_PremiumIncome_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIFillInfo_PremiumIncome_get(swigCPtr);
      return ret;
    } 
  }

  public double PremiumPay {
    set {
      TapTradePINVOKE.TapAPIFillInfo_PremiumPay_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIFillInfo_PremiumPay_get(swigCPtr);
      return ret;
    } 
  }

  public string OppoMatchNo {
    set {
      TapTradePINVOKE.TapAPIFillInfo_OppoMatchNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIFillInfo_OppoMatchNo_get(swigCPtr);
      return ret;
    } 
  }

  public double CloseProfit {
    set {
      TapTradePINVOKE.TapAPIFillInfo_CloseProfit_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIFillInfo_CloseProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double UnExpProfit {
    set {
      TapTradePINVOKE.TapAPIFillInfo_UnExpProfit_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIFillInfo_UnExpProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double UpperMatchPrice {
    set {
      TapTradePINVOKE.TapAPIFillInfo_UpperMatchPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIFillInfo_UpperMatchPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double QuotePrice {
    set {
      TapTradePINVOKE.TapAPIFillInfo_QuotePrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIFillInfo_QuotePrice_get(swigCPtr);
      return ret;
    } 
  }

  public double ClosePL {
    set {
      TapTradePINVOKE.TapAPIFillInfo_ClosePL_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIFillInfo_ClosePL_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIFillInfo() : this(TapTradePINVOKE.new_TapAPIFillInfo__SWIG_0(), true) {
  }

  public TapAPIFillInfo(TapAPIFillInfo other) : this(TapTradePINVOKE.new_TapAPIFillInfo__SWIG_1(TapAPIFillInfo.getCPtr(other)), true) {
    if (TapTradePINVOKE.SWIGPendingException.Pending) throw TapTradePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
