/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace TapTradeAPI {

using System;
using System.Runtime.InteropServices;

public class TapAPIOrderInfoNotice : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIOrderInfoNotice(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TapAPIOrderInfoNotice obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPIOrderInfoNotice() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradePINVOKE.delete_TapAPIOrderInfoNotice(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public uint SessionID {
    set {
      TapTradePINVOKE.TapAPIOrderInfoNotice_SessionID_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradePINVOKE.TapAPIOrderInfoNotice_SessionID_get(swigCPtr);
      return ret;
    } 
  }

  public uint ErrorCode {
    set {
      TapTradePINVOKE.TapAPIOrderInfoNotice_ErrorCode_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradePINVOKE.TapAPIOrderInfoNotice_ErrorCode_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIOrderInfo OrderInfo {
    set {
      TapTradePINVOKE.TapAPIOrderInfoNotice_OrderInfo_set(swigCPtr, TapAPIOrderInfo.getCPtr(value));
    } 
    get {
      IntPtr cPtr = TapTradePINVOKE.TapAPIOrderInfoNotice_OrderInfo_get(swigCPtr);
      TapAPIOrderInfo ret = (cPtr == IntPtr.Zero) ? null : new TapAPIOrderInfo(cPtr, false);
      return ret;
    } 
  }

  public TapAPIOrderInfoNotice() : this(TapTradePINVOKE.new_TapAPIOrderInfoNotice__SWIG_0(), true) {
  }

  public TapAPIOrderInfoNotice(TapAPIOrderInfoNotice other) : this(TapTradePINVOKE.new_TapAPIOrderInfoNotice__SWIG_1(TapAPIOrderInfoNotice.getCPtr(other)), true) {
    if (TapTradePINVOKE.SWIGPendingException.Pending) throw TapTradePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
