/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace TapTradeAPI {

using System;
using System.Runtime.InteropServices;

public class TapAPITradeLoginAuth : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPITradeLoginAuth(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TapAPITradeLoginAuth obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPITradeLoginAuth() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradePINVOKE.delete_TapAPITradeLoginAuth(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public string UserNo {
    set {
      TapTradePINVOKE.TapAPITradeLoginAuth_UserNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPITradeLoginAuth_UserNo_get(swigCPtr);
      return ret;
    } 
  }

  public char ISModifyPassword {
    set {
      TapTradePINVOKE.TapAPITradeLoginAuth_ISModifyPassword_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPITradeLoginAuth_ISModifyPassword_get(swigCPtr);
      return ret;
    } 
  }

  public string Password {
    set {
      TapTradePINVOKE.TapAPITradeLoginAuth_Password_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPITradeLoginAuth_Password_get(swigCPtr);
      return ret;
    } 
  }

  public string NewPassword {
    set {
      TapTradePINVOKE.TapAPITradeLoginAuth_NewPassword_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPITradeLoginAuth_NewPassword_get(swigCPtr);
      return ret;
    } 
  }

  public char ISDDA {
    set {
      TapTradePINVOKE.TapAPITradeLoginAuth_ISDDA_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPITradeLoginAuth_ISDDA_get(swigCPtr);
      return ret;
    } 
  }

  public string DDASerialNo {
    set {
      TapTradePINVOKE.TapAPITradeLoginAuth_DDASerialNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPITradeLoginAuth_DDASerialNo_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPITradeLoginAuth() : this(TapTradePINVOKE.new_TapAPITradeLoginAuth__SWIG_0(), true) {
  }

  public TapAPITradeLoginAuth(TapAPITradeLoginAuth other) : this(TapTradePINVOKE.new_TapAPITradeLoginAuth__SWIG_1(TapAPITradeLoginAuth.getCPtr(other)), true) {
    if (TapTradePINVOKE.SWIGPendingException.Pending) throw TapTradePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
