/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace TapTradeAPI {

using System;
using System.Runtime.InteropServices;

public class TapAPICloseInfo : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPICloseInfo(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TapAPICloseInfo obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPICloseInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradePINVOKE.delete_TapAPICloseInfo(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public string AccountNo {
    set {
      TapTradePINVOKE.TapAPICloseInfo_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICloseInfo_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ParentAccountNo {
    set {
      TapTradePINVOKE.TapAPICloseInfo_ParentAccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICloseInfo_ParentAccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      TapTradePINVOKE.TapAPICloseInfo_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICloseInfo_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityType {
    set {
      TapTradePINVOKE.TapAPICloseInfo_CommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPICloseInfo_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      TapTradePINVOKE.TapAPICloseInfo_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICloseInfo_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo {
    set {
      TapTradePINVOKE.TapAPICloseInfo_ContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICloseInfo_ContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice {
    set {
      TapTradePINVOKE.TapAPICloseInfo_StrikePrice_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICloseInfo_StrikePrice_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag {
    set {
      TapTradePINVOKE.TapAPICloseInfo_CallOrPutFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPICloseInfo_CallOrPutFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string OpenOrderExchangeNo {
    set {
      TapTradePINVOKE.TapAPICloseInfo_OpenOrderExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICloseInfo_OpenOrderExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char OpenOrderCommodityType {
    set {
      TapTradePINVOKE.TapAPICloseInfo_OpenOrderCommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPICloseInfo_OpenOrderCommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string OpenOrderCommodityNo {
    set {
      TapTradePINVOKE.TapAPICloseInfo_OpenOrderCommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICloseInfo_OpenOrderCommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string CloseOrderExchangeNo {
    set {
      TapTradePINVOKE.TapAPICloseInfo_CloseOrderExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICloseInfo_CloseOrderExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CloseOrderCommodityType {
    set {
      TapTradePINVOKE.TapAPICloseInfo_CloseOrderCommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPICloseInfo_CloseOrderCommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CloseOrderCommodityNo {
    set {
      TapTradePINVOKE.TapAPICloseInfo_CloseOrderCommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICloseInfo_CloseOrderCommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public char OpenMatchSource {
    set {
      TapTradePINVOKE.TapAPICloseInfo_OpenMatchSource_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPICloseInfo_OpenMatchSource_get(swigCPtr);
      return ret;
    } 
  }

  public char CloseMatchSource {
    set {
      TapTradePINVOKE.TapAPICloseInfo_CloseMatchSource_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPICloseInfo_CloseMatchSource_get(swigCPtr);
      return ret;
    } 
  }

  public char CloseSide {
    set {
      TapTradePINVOKE.TapAPICloseInfo_CloseSide_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPICloseInfo_CloseSide_get(swigCPtr);
      return ret;
    } 
  }

  public uint CloseQty {
    set {
      TapTradePINVOKE.TapAPICloseInfo_CloseQty_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradePINVOKE.TapAPICloseInfo_CloseQty_get(swigCPtr);
      return ret;
    } 
  }

  public double OpenPrice {
    set {
      TapTradePINVOKE.TapAPICloseInfo_OpenPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPICloseInfo_OpenPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double ClosePrice {
    set {
      TapTradePINVOKE.TapAPICloseInfo_ClosePrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPICloseInfo_ClosePrice_get(swigCPtr);
      return ret;
    } 
  }

  public char OpenServerFlag {
    set {
      TapTradePINVOKE.TapAPICloseInfo_OpenServerFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPICloseInfo_OpenServerFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string OpenOrderNo {
    set {
      TapTradePINVOKE.TapAPICloseInfo_OpenOrderNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICloseInfo_OpenOrderNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OpenMatchNo {
    set {
      TapTradePINVOKE.TapAPICloseInfo_OpenMatchNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICloseInfo_OpenMatchNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OpenExchangeMatchNo {
    set {
      TapTradePINVOKE.TapAPICloseInfo_OpenExchangeMatchNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICloseInfo_OpenExchangeMatchNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OpenMatchDateTime {
    set {
      TapTradePINVOKE.TapAPICloseInfo_OpenMatchDateTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICloseInfo_OpenMatchDateTime_get(swigCPtr);
      return ret;
    } 
  }

  public char CloseServerFlag {
    set {
      TapTradePINVOKE.TapAPICloseInfo_CloseServerFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPICloseInfo_CloseServerFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string CloseOrderNo {
    set {
      TapTradePINVOKE.TapAPICloseInfo_CloseOrderNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICloseInfo_CloseOrderNo_get(swigCPtr);
      return ret;
    } 
  }

  public string CloseMatchNo {
    set {
      TapTradePINVOKE.TapAPICloseInfo_CloseMatchNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICloseInfo_CloseMatchNo_get(swigCPtr);
      return ret;
    } 
  }

  public string CloseExchangeMatchNo {
    set {
      TapTradePINVOKE.TapAPICloseInfo_CloseExchangeMatchNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICloseInfo_CloseExchangeMatchNo_get(swigCPtr);
      return ret;
    } 
  }

  public string CloseMatchDateTime {
    set {
      TapTradePINVOKE.TapAPICloseInfo_CloseMatchDateTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICloseInfo_CloseMatchDateTime_get(swigCPtr);
      return ret;
    } 
  }

  public uint CloseStreamId {
    set {
      TapTradePINVOKE.TapAPICloseInfo_CloseStreamId_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradePINVOKE.TapAPICloseInfo_CloseStreamId_get(swigCPtr);
      return ret;
    } 
  }

  public char OpenCloseMode {
    set {
      TapTradePINVOKE.TapAPICloseInfo_OpenCloseMode_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPICloseInfo_OpenCloseMode_get(swigCPtr);
      return ret;
    } 
  }

  public double ContractSize {
    set {
      TapTradePINVOKE.TapAPICloseInfo_ContractSize_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPICloseInfo_ContractSize_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityCurrencyGroup {
    set {
      TapTradePINVOKE.TapAPICloseInfo_CommodityCurrencyGroup_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICloseInfo_CommodityCurrencyGroup_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityCurrency {
    set {
      TapTradePINVOKE.TapAPICloseInfo_CommodityCurrency_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICloseInfo_CommodityCurrency_get(swigCPtr);
      return ret;
    } 
  }

  public double PreSettlePrice {
    set {
      TapTradePINVOKE.TapAPICloseInfo_PreSettlePrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPICloseInfo_PreSettlePrice_get(swigCPtr);
      return ret;
    } 
  }

  public double PremiumIncome {
    set {
      TapTradePINVOKE.TapAPICloseInfo_PremiumIncome_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPICloseInfo_PremiumIncome_get(swigCPtr);
      return ret;
    } 
  }

  public double PremiumPay {
    set {
      TapTradePINVOKE.TapAPICloseInfo_PremiumPay_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPICloseInfo_PremiumPay_get(swigCPtr);
      return ret;
    } 
  }

  public double CloseProfit {
    set {
      TapTradePINVOKE.TapAPICloseInfo_CloseProfit_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPICloseInfo_CloseProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double UnExpProfit {
    set {
      TapTradePINVOKE.TapAPICloseInfo_UnExpProfit_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPICloseInfo_UnExpProfit_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPICloseInfo() : this(TapTradePINVOKE.new_TapAPICloseInfo__SWIG_0(), true) {
  }

  public TapAPICloseInfo(TapAPICloseInfo other) : this(TapTradePINVOKE.new_TapAPICloseInfo__SWIG_1(TapAPICloseInfo.getCPtr(other)), true) {
    if (TapTradePINVOKE.SWIGPendingException.Pending) throw TapTradePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
