/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace TapTradeAPI {

using System;
using System.Runtime.InteropServices;

public class TapAPICommodityInfo : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPICommodityInfo(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TapAPICommodityInfo obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPICommodityInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradePINVOKE.delete_TapAPICommodityInfo(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public string ExchangeNo {
    set {
      TapTradePINVOKE.TapAPICommodityInfo_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICommodityInfo_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityType {
    set {
      TapTradePINVOKE.TapAPICommodityInfo_CommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPICommodityInfo_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      TapTradePINVOKE.TapAPICommodityInfo_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICommodityInfo_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityName {
    set {
      TapTradePINVOKE.TapAPICommodityInfo_CommodityName_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICommodityInfo_CommodityName_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityEngName {
    set {
      TapTradePINVOKE.TapAPICommodityInfo_CommodityEngName_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICommodityInfo_CommodityEngName_get(swigCPtr);
      return ret;
    } 
  }

  public string RelateExchangeNo {
    set {
      TapTradePINVOKE.TapAPICommodityInfo_RelateExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICommodityInfo_RelateExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char RelateCommodityType {
    set {
      TapTradePINVOKE.TapAPICommodityInfo_RelateCommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPICommodityInfo_RelateCommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string RelateCommodityNo {
    set {
      TapTradePINVOKE.TapAPICommodityInfo_RelateCommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICommodityInfo_RelateCommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string RelateExchangeNo2 {
    set {
      TapTradePINVOKE.TapAPICommodityInfo_RelateExchangeNo2_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICommodityInfo_RelateExchangeNo2_get(swigCPtr);
      return ret;
    } 
  }

  public char RelateCommodityType2 {
    set {
      TapTradePINVOKE.TapAPICommodityInfo_RelateCommodityType2_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPICommodityInfo_RelateCommodityType2_get(swigCPtr);
      return ret;
    } 
  }

  public string RelateCommodityNo2 {
    set {
      TapTradePINVOKE.TapAPICommodityInfo_RelateCommodityNo2_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICommodityInfo_RelateCommodityNo2_get(swigCPtr);
      return ret;
    } 
  }

  public string TradeCurrency {
    set {
      TapTradePINVOKE.TapAPICommodityInfo_TradeCurrency_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICommodityInfo_TradeCurrency_get(swigCPtr);
      return ret;
    } 
  }

  public string SettleCurrency {
    set {
      TapTradePINVOKE.TapAPICommodityInfo_SettleCurrency_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICommodityInfo_SettleCurrency_get(swigCPtr);
      return ret;
    } 
  }

  public double ContractSize {
    set {
      TapTradePINVOKE.TapAPICommodityInfo_ContractSize_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPICommodityInfo_ContractSize_get(swigCPtr);
      return ret;
    } 
  }

  public char MarginCalculateMode {
    set {
      TapTradePINVOKE.TapAPICommodityInfo_MarginCalculateMode_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPICommodityInfo_MarginCalculateMode_get(swigCPtr);
      return ret;
    } 
  }

  public char OptionMarginCalculateMode {
    set {
      TapTradePINVOKE.TapAPICommodityInfo_OptionMarginCalculateMode_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPICommodityInfo_OptionMarginCalculateMode_get(swigCPtr);
      return ret;
    } 
  }

  public char OpenCloseMode {
    set {
      TapTradePINVOKE.TapAPICommodityInfo_OpenCloseMode_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPICommodityInfo_OpenCloseMode_get(swigCPtr);
      return ret;
    } 
  }

  public double StrikePriceTimes {
    set {
      TapTradePINVOKE.TapAPICommodityInfo_StrikePriceTimes_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPICommodityInfo_StrikePriceTimes_get(swigCPtr);
      return ret;
    } 
  }

  public char IsOnlyQuoteCommodity {
    set {
      TapTradePINVOKE.TapAPICommodityInfo_IsOnlyQuoteCommodity_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPICommodityInfo_IsOnlyQuoteCommodity_get(swigCPtr);
      return ret;
    } 
  }

  public double CommodityTickSize {
    set {
      TapTradePINVOKE.TapAPICommodityInfo_CommodityTickSize_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPICommodityInfo_CommodityTickSize_get(swigCPtr);
      return ret;
    } 
  }

  public int CommodityDenominator {
    set {
      TapTradePINVOKE.TapAPICommodityInfo_CommodityDenominator_set(swigCPtr, value);
    } 
    get {
      int ret = TapTradePINVOKE.TapAPICommodityInfo_CommodityDenominator_get(swigCPtr);
      return ret;
    } 
  }

  public char CmbDirect {
    set {
      TapTradePINVOKE.TapAPICommodityInfo_CmbDirect_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPICommodityInfo_CmbDirect_get(swigCPtr);
      return ret;
    } 
  }

  public int OnlyCanCloseDays {
    set {
      TapTradePINVOKE.TapAPICommodityInfo_OnlyCanCloseDays_set(swigCPtr, value);
    } 
    get {
      int ret = TapTradePINVOKE.TapAPICommodityInfo_OnlyCanCloseDays_get(swigCPtr);
      return ret;
    } 
  }

  public char DeliveryMode {
    set {
      TapTradePINVOKE.TapAPICommodityInfo_DeliveryMode_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPICommodityInfo_DeliveryMode_get(swigCPtr);
      return ret;
    } 
  }

  public int DeliveryDays {
    set {
      TapTradePINVOKE.TapAPICommodityInfo_DeliveryDays_set(swigCPtr, value);
    } 
    get {
      int ret = TapTradePINVOKE.TapAPICommodityInfo_DeliveryDays_get(swigCPtr);
      return ret;
    } 
  }

  public string AddOneTime {
    set {
      TapTradePINVOKE.TapAPICommodityInfo_AddOneTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICommodityInfo_AddOneTime_get(swigCPtr);
      return ret;
    } 
  }

  public int CommodityTimeZone {
    set {
      TapTradePINVOKE.TapAPICommodityInfo_CommodityTimeZone_set(swigCPtr, value);
    } 
    get {
      int ret = TapTradePINVOKE.TapAPICommodityInfo_CommodityTimeZone_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPICommodityInfo() : this(TapTradePINVOKE.new_TapAPICommodityInfo__SWIG_0(), true) {
  }

  public TapAPICommodityInfo(TapAPICommodityInfo other) : this(TapTradePINVOKE.new_TapAPICommodityInfo__SWIG_1(TapAPICommodityInfo.getCPtr(other)), true) {
    if (TapTradePINVOKE.SWIGPendingException.Pending) throw TapTradePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
