/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace TapTradeAPI {

using System;
using System.Runtime.InteropServices;

public class TapAPICommodity : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPICommodity(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TapAPICommodity obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPICommodity() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradePINVOKE.delete_TapAPICommodity(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public string ExchangeNo {
    set {
      TapTradePINVOKE.TapAPICommodity_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICommodity_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityType {
    set {
      TapTradePINVOKE.TapAPICommodity_CommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPICommodity_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      TapTradePINVOKE.TapAPICommodity_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICommodity_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPICommodity() : this(TapTradePINVOKE.new_TapAPICommodity__SWIG_0(), true) {
  }

  public TapAPICommodity(TapAPICommodity other) : this(TapTradePINVOKE.new_TapAPICommodity__SWIG_1(TapAPICommodity.getCPtr(other)), true) {
    if (TapTradePINVOKE.SWIGPendingException.Pending) throw TapTradePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
