/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace TapTradeAPI {

using System;
using System.Runtime.InteropServices;

public class TapAPITradeContractInfo : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPITradeContractInfo(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TapAPITradeContractInfo obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPITradeContractInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradePINVOKE.delete_TapAPITradeContractInfo(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public string ExchangeNo {
    set {
      TapTradePINVOKE.TapAPITradeContractInfo_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPITradeContractInfo_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityType {
    set {
      TapTradePINVOKE.TapAPITradeContractInfo_CommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPITradeContractInfo_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      TapTradePINVOKE.TapAPITradeContractInfo_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPITradeContractInfo_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo1 {
    set {
      TapTradePINVOKE.TapAPITradeContractInfo_ContractNo1_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPITradeContractInfo_ContractNo1_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice1 {
    set {
      TapTradePINVOKE.TapAPITradeContractInfo_StrikePrice1_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPITradeContractInfo_StrikePrice1_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag1 {
    set {
      TapTradePINVOKE.TapAPITradeContractInfo_CallOrPutFlag1_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPITradeContractInfo_CallOrPutFlag1_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo2 {
    set {
      TapTradePINVOKE.TapAPITradeContractInfo_ContractNo2_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPITradeContractInfo_ContractNo2_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice2 {
    set {
      TapTradePINVOKE.TapAPITradeContractInfo_StrikePrice2_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPITradeContractInfo_StrikePrice2_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag2 {
    set {
      TapTradePINVOKE.TapAPITradeContractInfo_CallOrPutFlag2_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPITradeContractInfo_CallOrPutFlag2_get(swigCPtr);
      return ret;
    } 
  }

  public char ContractType {
    set {
      TapTradePINVOKE.TapAPITradeContractInfo_ContractType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPITradeContractInfo_ContractType_get(swigCPtr);
      return ret;
    } 
  }

  public string QuoteUnderlyingContract {
    set {
      TapTradePINVOKE.TapAPITradeContractInfo_QuoteUnderlyingContract_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPITradeContractInfo_QuoteUnderlyingContract_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractName {
    set {
      TapTradePINVOKE.TapAPITradeContractInfo_ContractName_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPITradeContractInfo_ContractName_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractExpDate {
    set {
      TapTradePINVOKE.TapAPITradeContractInfo_ContractExpDate_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPITradeContractInfo_ContractExpDate_get(swigCPtr);
      return ret;
    } 
  }

  public string LastTradeDate {
    set {
      TapTradePINVOKE.TapAPITradeContractInfo_LastTradeDate_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPITradeContractInfo_LastTradeDate_get(swigCPtr);
      return ret;
    } 
  }

  public string FirstNoticeDate {
    set {
      TapTradePINVOKE.TapAPITradeContractInfo_FirstNoticeDate_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPITradeContractInfo_FirstNoticeDate_get(swigCPtr);
      return ret;
    } 
  }

  public string FutureContractNo {
    set {
      TapTradePINVOKE.TapAPITradeContractInfo_FutureContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPITradeContractInfo_FutureContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPITradeContractInfo() : this(TapTradePINVOKE.new_TapAPITradeContractInfo__SWIG_0(), true) {
  }

  public TapAPITradeContractInfo(TapAPITradeContractInfo other) : this(TapTradePINVOKE.new_TapAPITradeContractInfo__SWIG_1(TapAPITradeContractInfo.getCPtr(other)), true) {
    if (TapTradePINVOKE.SWIGPendingException.Pending) throw TapTradePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
