/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace TapTradeAPI {

using System;
using System.Runtime.InteropServices;

public class TapAPIOrderProcessQryReq : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIOrderProcessQryReq(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TapAPIOrderProcessQryReq obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPIOrderProcessQryReq() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradePINVOKE.delete_TapAPIOrderProcessQryReq(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public char ServerFlag {
    set {
      TapTradePINVOKE.TapAPIOrderProcessQryReq_ServerFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIOrderProcessQryReq_ServerFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderNo {
    set {
      TapTradePINVOKE.TapAPIOrderProcessQryReq_OrderNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderProcessQryReq_OrderNo_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIOrderProcessQryReq() : this(TapTradePINVOKE.new_TapAPIOrderProcessQryReq__SWIG_0(), true) {
  }

  public TapAPIOrderProcessQryReq(TapAPIOrderProcessQryReq other) : this(TapTradePINVOKE.new_TapAPIOrderProcessQryReq__SWIG_1(TapAPIOrderProcessQryReq.getCPtr(other)), true) {
    if (TapTradePINVOKE.SWIGPendingException.Pending) throw TapTradePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
