/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace TapTradeAPI {

using System;
using System.Runtime.InteropServices;

public class TapAPIExchangeStateInfo : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIExchangeStateInfo(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TapAPIExchangeStateInfo obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPIExchangeStateInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradePINVOKE.delete_TapAPIExchangeStateInfo(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public string UpperChannelNo {
    set {
      TapTradePINVOKE.TapAPIExchangeStateInfo_UpperChannelNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIExchangeStateInfo_UpperChannelNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      TapTradePINVOKE.TapAPIExchangeStateInfo_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIExchangeStateInfo_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityType {
    set {
      TapTradePINVOKE.TapAPIExchangeStateInfo_CommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIExchangeStateInfo_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      TapTradePINVOKE.TapAPIExchangeStateInfo_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIExchangeStateInfo_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeTime {
    set {
      TapTradePINVOKE.TapAPIExchangeStateInfo_ExchangeTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIExchangeStateInfo_ExchangeTime_get(swigCPtr);
      return ret;
    } 
  }

  public char TradingState {
    set {
      TapTradePINVOKE.TapAPIExchangeStateInfo_TradingState_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIExchangeStateInfo_TradingState_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIExchangeStateInfo() : this(TapTradePINVOKE.new_TapAPIExchangeStateInfo__SWIG_0(), true) {
  }

  public TapAPIExchangeStateInfo(TapAPIExchangeStateInfo other) : this(TapTradePINVOKE.new_TapAPIExchangeStateInfo__SWIG_1(TapAPIExchangeStateInfo.getCPtr(other)), true) {
    if (TapTradePINVOKE.SWIGPendingException.Pending) throw TapTradePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
