/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace TapTradeAPI {

using System;
using System.Runtime.InteropServices;

public class TapAPIOrderInfo : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIOrderInfo(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TapAPIOrderInfo obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPIOrderInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradePINVOKE.delete_TapAPIOrderInfo(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public string AccountNo {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityType {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_CommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIOrderInfo_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_ContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_ContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_StrikePrice_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_StrikePrice_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_CallOrPutFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIOrderInfo_CallOrPutFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo2 {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_ContractNo2_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_ContractNo2_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice2 {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_StrikePrice2_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_StrikePrice2_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag2 {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_CallOrPutFlag2_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIOrderInfo_CallOrPutFlag2_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderType {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_OrderType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIOrderInfo_OrderType_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderSource {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_OrderSource_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIOrderInfo_OrderSource_get(swigCPtr);
      return ret;
    } 
  }

  public char TimeInForce {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_TimeInForce_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIOrderInfo_TimeInForce_get(swigCPtr);
      return ret;
    } 
  }

  public string ExpireTime {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_ExpireTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_ExpireTime_get(swigCPtr);
      return ret;
    } 
  }

  public char IsRiskOrder {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_IsRiskOrder_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIOrderInfo_IsRiskOrder_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderSide {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_OrderSide_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIOrderInfo_OrderSide_get(swigCPtr);
      return ret;
    } 
  }

  public char PositionEffect {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_PositionEffect_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIOrderInfo_PositionEffect_get(swigCPtr);
      return ret;
    } 
  }

  public char PositionEffect2 {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_PositionEffect2_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIOrderInfo_PositionEffect2_get(swigCPtr);
      return ret;
    } 
  }

  public string InquiryNo {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_InquiryNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_InquiryNo_get(swigCPtr);
      return ret;
    } 
  }

  public char HedgeFlag {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_HedgeFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIOrderInfo_HedgeFlag_get(swigCPtr);
      return ret;
    } 
  }

  public double OrderPrice {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_OrderPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIOrderInfo_OrderPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double OrderPrice2 {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_OrderPrice2_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIOrderInfo_OrderPrice2_get(swigCPtr);
      return ret;
    } 
  }

  public double StopPrice {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_StopPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIOrderInfo_StopPrice_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderQty {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_OrderQty_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradePINVOKE.TapAPIOrderInfo_OrderQty_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderMinQty {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_OrderMinQty_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradePINVOKE.TapAPIOrderInfo_OrderMinQty_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderCanceledQty {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_OrderCanceledQty_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradePINVOKE.TapAPIOrderInfo_OrderCanceledQty_get(swigCPtr);
      return ret;
    } 
  }

  public uint MinClipSize {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_MinClipSize_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradePINVOKE.TapAPIOrderInfo_MinClipSize_get(swigCPtr);
      return ret;
    } 
  }

  public uint MaxClipSize {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_MaxClipSize_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradePINVOKE.TapAPIOrderInfo_MaxClipSize_get(swigCPtr);
      return ret;
    } 
  }

  public string LicenseNo {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_LicenseNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_LicenseNo_get(swigCPtr);
      return ret;
    } 
  }

  public int RefInt {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_RefInt_set(swigCPtr, value);
    } 
    get {
      int ret = TapTradePINVOKE.TapAPIOrderInfo_RefInt_get(swigCPtr);
      return ret;
    } 
  }

  public string RefString {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_RefString_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_RefString_get(swigCPtr);
      return ret;
    } 
  }

  public string ParentAccountNo {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_ParentAccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_ParentAccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public char ServerFlag {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_ServerFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIOrderInfo_ServerFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderNo {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_OrderNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_OrderNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ClientOrderNo {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_ClientOrderNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_ClientOrderNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderLocalNo {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_OrderLocalNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_OrderLocalNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderSystemNo {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_OrderSystemNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_OrderSystemNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderExchangeSystemNo {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_OrderExchangeSystemNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_OrderExchangeSystemNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderParentNo {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_OrderParentNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_OrderParentNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderParentSystemNo {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_OrderParentSystemNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_OrderParentSystemNo_get(swigCPtr);
      return ret;
    } 
  }

  public string TradeNo {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_TradeNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_TradeNo_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperNo {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_UpperNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_UpperNo_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperChannelNo {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_UpperChannelNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_UpperChannelNo_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperSettleNo {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_UpperSettleNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_UpperSettleNo_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperUserNo {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_UpperUserNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_UpperUserNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderInsertUserNo {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_OrderInsertUserNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_OrderInsertUserNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderInsertTime {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_OrderInsertTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_OrderInsertTime_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderCommandUserNo {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_OrderCommandUserNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_OrderCommandUserNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderUpdateUserNo {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_OrderUpdateUserNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_OrderUpdateUserNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderUpdateTime {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_OrderUpdateTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_OrderUpdateTime_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderState {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_OrderState_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIOrderInfo_OrderState_get(swigCPtr);
      return ret;
    } 
  }

  public double OrderMatchPrice {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_OrderMatchPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIOrderInfo_OrderMatchPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double OrderMatchPrice2 {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_OrderMatchPrice2_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIOrderInfo_OrderMatchPrice2_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderMatchQty {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_OrderMatchQty_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradePINVOKE.TapAPIOrderInfo_OrderMatchQty_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderMatchQty2 {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_OrderMatchQty2_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradePINVOKE.TapAPIOrderInfo_OrderMatchQty2_get(swigCPtr);
      return ret;
    } 
  }

  public uint ErrorCode {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_ErrorCode_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradePINVOKE.TapAPIOrderInfo_ErrorCode_get(swigCPtr);
      return ret;
    } 
  }

  public string ErrorText {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_ErrorText_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_ErrorText_get(swigCPtr);
      return ret;
    } 
  }

  public char IsBackInput {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_IsBackInput_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIOrderInfo_IsBackInput_get(swigCPtr);
      return ret;
    } 
  }

  public char IsDeleted {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_IsDeleted_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIOrderInfo_IsDeleted_get(swigCPtr);
      return ret;
    } 
  }

  public char IsAddOne {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_IsAddOne_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIOrderInfo_IsAddOne_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderStreamID {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_OrderStreamID_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradePINVOKE.TapAPIOrderInfo_OrderStreamID_get(swigCPtr);
      return ret;
    } 
  }

  public uint UpperStreamID {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_UpperStreamID_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradePINVOKE.TapAPIOrderInfo_UpperStreamID_get(swigCPtr);
      return ret;
    } 
  }

  public double ContractSize {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_ContractSize_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIOrderInfo_ContractSize_get(swigCPtr);
      return ret;
    } 
  }

  public double ContractSize2 {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_ContractSize2_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIOrderInfo_ContractSize2_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityCurrencyGroup {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_CommodityCurrencyGroup_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_CommodityCurrencyGroup_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityCurrency {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_CommodityCurrency_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_CommodityCurrency_get(swigCPtr);
      return ret;
    } 
  }

  public char FeeMode {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_FeeMode_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIOrderInfo_FeeMode_get(swigCPtr);
      return ret;
    } 
  }

  public double FeeParam {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_FeeParam_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIOrderInfo_FeeParam_get(swigCPtr);
      return ret;
    } 
  }

  public string FeeCurrencyGroup {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_FeeCurrencyGroup_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_FeeCurrencyGroup_get(swigCPtr);
      return ret;
    } 
  }

  public string FeeCurrency {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_FeeCurrency_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_FeeCurrency_get(swigCPtr);
      return ret;
    } 
  }

  public char FeeMode2 {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_FeeMode2_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIOrderInfo_FeeMode2_get(swigCPtr);
      return ret;
    } 
  }

  public double FeeParam2 {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_FeeParam2_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIOrderInfo_FeeParam2_get(swigCPtr);
      return ret;
    } 
  }

  public string FeeCurrencyGroup2 {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_FeeCurrencyGroup2_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_FeeCurrencyGroup2_get(swigCPtr);
      return ret;
    } 
  }

  public string FeeCurrency2 {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_FeeCurrency2_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIOrderInfo_FeeCurrency2_get(swigCPtr);
      return ret;
    } 
  }

  public char MarginMode {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_MarginMode_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIOrderInfo_MarginMode_get(swigCPtr);
      return ret;
    } 
  }

  public double MarginParam {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_MarginParam_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIOrderInfo_MarginParam_get(swigCPtr);
      return ret;
    } 
  }

  public char MarginMode2 {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_MarginMode2_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIOrderInfo_MarginMode2_get(swigCPtr);
      return ret;
    } 
  }

  public double MarginParam2 {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_MarginParam2_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIOrderInfo_MarginParam2_get(swigCPtr);
      return ret;
    } 
  }

  public double PreSettlePrice {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_PreSettlePrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIOrderInfo_PreSettlePrice_get(swigCPtr);
      return ret;
    } 
  }

  public double PreSettlePrice2 {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_PreSettlePrice2_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIOrderInfo_PreSettlePrice2_get(swigCPtr);
      return ret;
    } 
  }

  public uint OpenVol {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_OpenVol_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradePINVOKE.TapAPIOrderInfo_OpenVol_get(swigCPtr);
      return ret;
    } 
  }

  public uint CoverVol {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_CoverVol_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradePINVOKE.TapAPIOrderInfo_CoverVol_get(swigCPtr);
      return ret;
    } 
  }

  public uint OpenVol2 {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_OpenVol2_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradePINVOKE.TapAPIOrderInfo_OpenVol2_get(swigCPtr);
      return ret;
    } 
  }

  public uint CoverVol2 {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_CoverVol2_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradePINVOKE.TapAPIOrderInfo_CoverVol2_get(swigCPtr);
      return ret;
    } 
  }

  public double FeeValue {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_FeeValue_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIOrderInfo_FeeValue_get(swigCPtr);
      return ret;
    } 
  }

  public double MarginValue {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_MarginValue_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIOrderInfo_MarginValue_get(swigCPtr);
      return ret;
    } 
  }

  public char TacticsType {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_TacticsType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIOrderInfo_TacticsType_get(swigCPtr);
      return ret;
    } 
  }

  public char TriggerCondition {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_TriggerCondition_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIOrderInfo_TriggerCondition_get(swigCPtr);
      return ret;
    } 
  }

  public char TriggerPriceType {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_TriggerPriceType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIOrderInfo_TriggerPriceType_get(swigCPtr);
      return ret;
    } 
  }

  public char AddOneIsValid {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_AddOneIsValid_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIOrderInfo_AddOneIsValid_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderQty2 {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_OrderQty2_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradePINVOKE.TapAPIOrderInfo_OrderQty2_get(swigCPtr);
      return ret;
    } 
  }

  public char HedgeFlag2 {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_HedgeFlag2_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIOrderInfo_HedgeFlag2_get(swigCPtr);
      return ret;
    } 
  }

  public byte MarketLevel {
    set {
      TapTradePINVOKE.TapAPIOrderInfo_MarketLevel_set(swigCPtr, value);
    } 
    get {
      byte ret = TapTradePINVOKE.TapAPIOrderInfo_MarketLevel_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIOrderInfo() : this(TapTradePINVOKE.new_TapAPIOrderInfo__SWIG_0(), true) {
  }

  public TapAPIOrderInfo(TapAPIOrderInfo other) : this(TapTradePINVOKE.new_TapAPIOrderInfo__SWIG_1(TapAPIOrderInfo.getCPtr(other)), false) {
    if (TapTradePINVOKE.SWIGPendingException.Pending) throw TapTradePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
