/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace TapTradeAPI {

using System;
using System.Runtime.InteropServices;

public class TapAPINewOrder : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPINewOrder(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TapAPINewOrder obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPINewOrder() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradePINVOKE.delete_TapAPINewOrder(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public string AccountNo {
    set {
      TapTradePINVOKE.TapAPINewOrder_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPINewOrder_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      TapTradePINVOKE.TapAPINewOrder_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPINewOrder_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityType {
    set {
      TapTradePINVOKE.TapAPINewOrder_CommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPINewOrder_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      TapTradePINVOKE.TapAPINewOrder_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPINewOrder_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo {
    set {
      TapTradePINVOKE.TapAPINewOrder_ContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPINewOrder_ContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice {
    set {
      TapTradePINVOKE.TapAPINewOrder_StrikePrice_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPINewOrder_StrikePrice_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag {
    set {
      TapTradePINVOKE.TapAPINewOrder_CallOrPutFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPINewOrder_CallOrPutFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo2 {
    set {
      TapTradePINVOKE.TapAPINewOrder_ContractNo2_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPINewOrder_ContractNo2_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice2 {
    set {
      TapTradePINVOKE.TapAPINewOrder_StrikePrice2_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPINewOrder_StrikePrice2_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag2 {
    set {
      TapTradePINVOKE.TapAPINewOrder_CallOrPutFlag2_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPINewOrder_CallOrPutFlag2_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderType {
    set {
      TapTradePINVOKE.TapAPINewOrder_OrderType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPINewOrder_OrderType_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderSource {
    set {
      TapTradePINVOKE.TapAPINewOrder_OrderSource_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPINewOrder_OrderSource_get(swigCPtr);
      return ret;
    } 
  }

  public char TimeInForce {
    set {
      TapTradePINVOKE.TapAPINewOrder_TimeInForce_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPINewOrder_TimeInForce_get(swigCPtr);
      return ret;
    } 
  }

  public string ExpireTime {
    set {
      TapTradePINVOKE.TapAPINewOrder_ExpireTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPINewOrder_ExpireTime_get(swigCPtr);
      return ret;
    } 
  }

  public char IsRiskOrder {
    set {
      TapTradePINVOKE.TapAPINewOrder_IsRiskOrder_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPINewOrder_IsRiskOrder_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderSide {
    set {
      TapTradePINVOKE.TapAPINewOrder_OrderSide_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPINewOrder_OrderSide_get(swigCPtr);
      return ret;
    } 
  }

  public char PositionEffect {
    set {
      TapTradePINVOKE.TapAPINewOrder_PositionEffect_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPINewOrder_PositionEffect_get(swigCPtr);
      return ret;
    } 
  }

  public char PositionEffect2 {
    set {
      TapTradePINVOKE.TapAPINewOrder_PositionEffect2_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPINewOrder_PositionEffect2_get(swigCPtr);
      return ret;
    } 
  }

  public string InquiryNo {
    set {
      TapTradePINVOKE.TapAPINewOrder_InquiryNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPINewOrder_InquiryNo_get(swigCPtr);
      return ret;
    } 
  }

  public char HedgeFlag {
    set {
      TapTradePINVOKE.TapAPINewOrder_HedgeFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPINewOrder_HedgeFlag_get(swigCPtr);
      return ret;
    } 
  }

  public double OrderPrice {
    set {
      TapTradePINVOKE.TapAPINewOrder_OrderPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPINewOrder_OrderPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double OrderPrice2 {
    set {
      TapTradePINVOKE.TapAPINewOrder_OrderPrice2_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPINewOrder_OrderPrice2_get(swigCPtr);
      return ret;
    } 
  }

  public double StopPrice {
    set {
      TapTradePINVOKE.TapAPINewOrder_StopPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPINewOrder_StopPrice_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderQty {
    set {
      TapTradePINVOKE.TapAPINewOrder_OrderQty_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradePINVOKE.TapAPINewOrder_OrderQty_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderMinQty {
    set {
      TapTradePINVOKE.TapAPINewOrder_OrderMinQty_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradePINVOKE.TapAPINewOrder_OrderMinQty_get(swigCPtr);
      return ret;
    } 
  }

  public uint MinClipSize {
    set {
      TapTradePINVOKE.TapAPINewOrder_MinClipSize_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradePINVOKE.TapAPINewOrder_MinClipSize_get(swigCPtr);
      return ret;
    } 
  }

  public uint MaxClipSize {
    set {
      TapTradePINVOKE.TapAPINewOrder_MaxClipSize_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradePINVOKE.TapAPINewOrder_MaxClipSize_get(swigCPtr);
      return ret;
    } 
  }

  public int RefInt {
    set {
      TapTradePINVOKE.TapAPINewOrder_RefInt_set(swigCPtr, value);
    } 
    get {
      int ret = TapTradePINVOKE.TapAPINewOrder_RefInt_get(swigCPtr);
      return ret;
    } 
  }

  public string RefString {
    set {
      TapTradePINVOKE.TapAPINewOrder_RefString_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPINewOrder_RefString_get(swigCPtr);
      return ret;
    } 
  }

  public char TacticsType {
    set {
      TapTradePINVOKE.TapAPINewOrder_TacticsType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPINewOrder_TacticsType_get(swigCPtr);
      return ret;
    } 
  }

  public char TriggerCondition {
    set {
      TapTradePINVOKE.TapAPINewOrder_TriggerCondition_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPINewOrder_TriggerCondition_get(swigCPtr);
      return ret;
    } 
  }

  public char TriggerPriceType {
    set {
      TapTradePINVOKE.TapAPINewOrder_TriggerPriceType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPINewOrder_TriggerPriceType_get(swigCPtr);
      return ret;
    } 
  }

  public char AddOneIsValid {
    set {
      TapTradePINVOKE.TapAPINewOrder_AddOneIsValid_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPINewOrder_AddOneIsValid_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPINewOrder() : this(TapTradePINVOKE.new_TapAPINewOrder__SWIG_0(), true) {
  }

  public TapAPINewOrder(TapAPINewOrder other) : this(TapTradePINVOKE.new_TapAPINewOrder__SWIG_1(TapAPINewOrder.getCPtr(other)), true) {
    if (TapTradePINVOKE.SWIGPendingException.Pending) throw TapTradePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
