/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace TapTradeAPI {

using System;
using System.Runtime.InteropServices;

public class TapAPICommodityOrderTimeInForceQryRsp : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPICommodityOrderTimeInForceQryRsp(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TapAPICommodityOrderTimeInForceQryRsp obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPICommodityOrderTimeInForceQryRsp() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradePINVOKE.delete_TapAPICommodityOrderTimeInForceQryRsp(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public TapAPICommodity Commodity {
    set {
      TapTradePINVOKE.TapAPICommodityOrderTimeInForceQryRsp_Commodity_set(swigCPtr, TapAPICommodity.getCPtr(value));
    } 
    get {
      IntPtr cPtr = TapTradePINVOKE.TapAPICommodityOrderTimeInForceQryRsp_Commodity_get(swigCPtr);
      TapAPICommodity ret = (cPtr == IntPtr.Zero) ? null : new TapAPICommodity(cPtr, false);
      return ret;
    } 
  }

  public int Count {
    set {
      TapTradePINVOKE.TapAPICommodityOrderTimeInForceQryRsp_Count_set(swigCPtr, value);
    } 
    get {
      int ret = TapTradePINVOKE.TapAPICommodityOrderTimeInForceQryRsp_Count_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderTimeInForces {
    set {
      TapTradePINVOKE.TapAPICommodityOrderTimeInForceQryRsp_OrderTimeInForces_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPICommodityOrderTimeInForceQryRsp_OrderTimeInForces_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPICommodityOrderTimeInForceQryRsp() : this(TapTradePINVOKE.new_TapAPICommodityOrderTimeInForceQryRsp__SWIG_0(), true) {
  }

  public TapAPICommodityOrderTimeInForceQryRsp(TapAPICommodityOrderTimeInForceQryRsp other) : this(TapTradePINVOKE.new_TapAPICommodityOrderTimeInForceQryRsp__SWIG_1(TapAPICommodityOrderTimeInForceQryRsp.getCPtr(other)), true) {
    if (TapTradePINVOKE.SWIGPendingException.Pending) throw TapTradePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
