/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace TapTradeAPI {

using System;
using System.Runtime.InteropServices;

public class TapAPIDeepQuoteInfo : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIDeepQuoteInfo(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TapAPIDeepQuoteInfo obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPIDeepQuoteInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradePINVOKE.delete_TapAPIDeepQuoteInfo(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public char Side {
    set {
      TapTradePINVOKE.TapAPIDeepQuoteInfo_Side_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIDeepQuoteInfo_Side_get(swigCPtr);
      return ret;
    } 
  }

  public double Price {
    set {
      TapTradePINVOKE.TapAPIDeepQuoteInfo_Price_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIDeepQuoteInfo_Price_get(swigCPtr);
      return ret;
    } 
  }

  public uint Qty {
    set {
      TapTradePINVOKE.TapAPIDeepQuoteInfo_Qty_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradePINVOKE.TapAPIDeepQuoteInfo_Qty_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIDeepQuoteInfo() : this(TapTradePINVOKE.new_TapAPIDeepQuoteInfo__SWIG_0(), true) {
  }

  public TapAPIDeepQuoteInfo(TapAPIDeepQuoteInfo other) : this(TapTradePINVOKE.new_TapAPIDeepQuoteInfo__SWIG_1(TapAPIDeepQuoteInfo.getCPtr(other)), true) {
    if (TapTradePINVOKE.SWIGPendingException.Pending) throw TapTradePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
