/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace TapTradeAPI {

using System;
using System.Runtime.InteropServices;

public class TapAPIPositionInfo : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIPositionInfo(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TapAPIPositionInfo obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPIPositionInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradePINVOKE.delete_TapAPIPositionInfo(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public string AccountNo {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIPositionInfo_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ParentAccountNo {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_ParentAccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIPositionInfo_ParentAccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIPositionInfo_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityType {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_CommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIPositionInfo_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIPositionInfo_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_ContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIPositionInfo_ContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_StrikePrice_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIPositionInfo_StrikePrice_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_CallOrPutFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIPositionInfo_CallOrPutFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNoRef {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_ExchangeNoRef_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIPositionInfo_ExchangeNoRef_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityTypeRef {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_CommodityTypeRef_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIPositionInfo_CommodityTypeRef_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNoRef {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_CommodityNoRef_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIPositionInfo_CommodityNoRef_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNoRef {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_ContractNoRef_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIPositionInfo_ContractNoRef_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePriceRef {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_StrikePriceRef_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIPositionInfo_StrikePriceRef_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlagRef {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_CallOrPutFlagRef_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIPositionInfo_CallOrPutFlagRef_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderExchangeNo {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_OrderExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIPositionInfo_OrderExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderCommodityType {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_OrderCommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIPositionInfo_OrderCommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderCommodityNo {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_OrderCommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIPositionInfo_OrderCommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderType {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_OrderType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIPositionInfo_OrderType_get(swigCPtr);
      return ret;
    } 
  }

  public char MatchSource {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_MatchSource_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIPositionInfo_MatchSource_get(swigCPtr);
      return ret;
    } 
  }

  public char TimeInForce {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_TimeInForce_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIPositionInfo_TimeInForce_get(swigCPtr);
      return ret;
    } 
  }

  public string ExpireTime {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_ExpireTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIPositionInfo_ExpireTime_get(swigCPtr);
      return ret;
    } 
  }

  public char MatchSide {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_MatchSide_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIPositionInfo_MatchSide_get(swigCPtr);
      return ret;
    } 
  }

  public char HedgeFlag {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_HedgeFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIPositionInfo_HedgeFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string PositionNo {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_PositionNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIPositionInfo_PositionNo_get(swigCPtr);
      return ret;
    } 
  }

  public char ServerFlag {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_ServerFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIPositionInfo_ServerFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderNo {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_OrderNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIPositionInfo_OrderNo_get(swigCPtr);
      return ret;
    } 
  }

  public string MatchNo {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_MatchNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIPositionInfo_MatchNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeMatchNo {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_ExchangeMatchNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIPositionInfo_ExchangeMatchNo_get(swigCPtr);
      return ret;
    } 
  }

  public string MatchDate {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_MatchDate_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIPositionInfo_MatchDate_get(swigCPtr);
      return ret;
    } 
  }

  public string MatchTime {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_MatchTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIPositionInfo_MatchTime_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperMatchTime {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_UpperMatchTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIPositionInfo_UpperMatchTime_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperNo {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_UpperNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIPositionInfo_UpperNo_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperSettleNo {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_UpperSettleNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIPositionInfo_UpperSettleNo_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperUserNo {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_UpperUserNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIPositionInfo_UpperUserNo_get(swigCPtr);
      return ret;
    } 
  }

  public string TradeNo {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_TradeNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIPositionInfo_TradeNo_get(swigCPtr);
      return ret;
    } 
  }

  public double PositionPrice {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_PositionPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIPositionInfo_PositionPrice_get(swigCPtr);
      return ret;
    } 
  }

  public uint PositionQty {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_PositionQty_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradePINVOKE.TapAPIPositionInfo_PositionQty_get(swigCPtr);
      return ret;
    } 
  }

  public char IsBackInput {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_IsBackInput_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIPositionInfo_IsBackInput_get(swigCPtr);
      return ret;
    } 
  }

  public char IsAddOne {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_IsAddOne_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIPositionInfo_IsAddOne_get(swigCPtr);
      return ret;
    } 
  }

  public uint MatchStreamID {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_MatchStreamID_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradePINVOKE.TapAPIPositionInfo_MatchStreamID_get(swigCPtr);
      return ret;
    } 
  }

  public uint PositionStreamId {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_PositionStreamId_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradePINVOKE.TapAPIPositionInfo_PositionStreamId_get(swigCPtr);
      return ret;
    } 
  }

  public char OpenCloseMode {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_OpenCloseMode_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIPositionInfo_OpenCloseMode_get(swigCPtr);
      return ret;
    } 
  }

  public double ContractSize {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_ContractSize_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIPositionInfo_ContractSize_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityCurrencyGroup {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_CommodityCurrencyGroup_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIPositionInfo_CommodityCurrencyGroup_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityCurrency {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_CommodityCurrency_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIPositionInfo_CommodityCurrency_get(swigCPtr);
      return ret;
    } 
  }

  public double PreSettlePrice {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_PreSettlePrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIPositionInfo_PreSettlePrice_get(swigCPtr);
      return ret;
    } 
  }

  public double SettlePrice {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_SettlePrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIPositionInfo_SettlePrice_get(swigCPtr);
      return ret;
    } 
  }

  public double Turnover {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_Turnover_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIPositionInfo_Turnover_get(swigCPtr);
      return ret;
    } 
  }

  public char AccountMarginMode {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_AccountMarginMode_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIPositionInfo_AccountMarginMode_get(swigCPtr);
      return ret;
    } 
  }

  public double AccountMarginParam {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_AccountMarginParam_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIPositionInfo_AccountMarginParam_get(swigCPtr);
      return ret;
    } 
  }

  public char UpperMarginMode {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_UpperMarginMode_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIPositionInfo_UpperMarginMode_get(swigCPtr);
      return ret;
    } 
  }

  public double UpperMarginParam {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_UpperMarginParam_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIPositionInfo_UpperMarginParam_get(swigCPtr);
      return ret;
    } 
  }

  public double AccountInitialMargin {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_AccountInitialMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIPositionInfo_AccountInitialMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double AccountMaintenanceMargin {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_AccountMaintenanceMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIPositionInfo_AccountMaintenanceMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double UpperInitialMargin {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_UpperInitialMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIPositionInfo_UpperInitialMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double UpperMaintenanceMargin {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_UpperMaintenanceMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIPositionInfo_UpperMaintenanceMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double PositionProfit {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_PositionProfit_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIPositionInfo_PositionProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double LMEPositionProfit {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_LMEPositionProfit_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIPositionInfo_LMEPositionProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double OptionMarketValue {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_OptionMarketValue_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradePINVOKE.TapAPIPositionInfo_OptionMarketValue_get(swigCPtr);
      return ret;
    } 
  }

  public string MatchCmbNo {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_MatchCmbNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradePINVOKE.TapAPIPositionInfo_MatchCmbNo_get(swigCPtr);
      return ret;
    } 
  }

  public char IsHistory {
    set {
      TapTradePINVOKE.TapAPIPositionInfo_IsHistory_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradePINVOKE.TapAPIPositionInfo_IsHistory_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIPositionInfo() : this(TapTradePINVOKE.new_TapAPIPositionInfo__SWIG_0(), true) {
  }

  public TapAPIPositionInfo(TapAPIPositionInfo other) : this(TapTradePINVOKE.new_TapAPIPositionInfo__SWIG_1(TapAPIPositionInfo.getCPtr(other)), true) {
    if (TapTradePINVOKE.SWIGPendingException.Pending) throw TapTradePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
